Repository kiwicom/orbit, pull requests merged in 2018-07, with the labels that each got.

#192 Update dependency babel-jest to v23.2.0
  package.json
  yarn.lock
Labels: dependency, renovate

#193 Update dependency jest to v23.3.0
  package.json
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  src/Radio/__tests__/__snapshots__/index.test.js.snap
  src/TextLink/__tests__/__snapshots__/index.test.js.snap
  yarn.lock
Labels: dependency, renovate

#190 Update dependency flow-bin to ^0.74.0
  package.json
  yarn.lock
Labels: dependency, renovate

#188 Update circleci/node Docker tag to v8.11
  .circleci/config.yml
Labels: dependency, renovate

#189 Update dependency @kiwicom/orbit-design-tokens to ^0.0.13
  package.json
  src/Alert/Alert.js
  src/Alert/Alert.js.flow
  src/Alert/__tests__/__snapshots__/index.test.js.snap
  src/Alert/__tests__/index.test.js
  src/Button/Button.js
  src/Button/Button.js.flow
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/ButtonLink.js
  src/ButtonLink/ButtonLink.js.flow
  src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/Card/Card.js
  src/Card/Card.js.flow
  src/Card/CardContent/CardContent.js
  src/Card/CardContent/CardContent.js.flow
  src/Card/CardHeader/CardHeader.js
  src/Card/CardHeader/CardHeader.js.flow
  src/Card/CardSection/CardSection.js
  src/Card/CardSection/CardSection.js.flow
  src/CarrierLogo/CarrierLogo.js
  src/CarrierLogo/CarrierLogo.js.flow
  src/CarrierLogo/__snapshots__/CarrierLogo.stories.storyshot
  src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/Checkbox.js
  src/Checkbox/Checkbox.js.flow
  src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  src/FormFeedback/FormFeedback.js
  src/FormFeedback/FormFeedback.js.flow
  src/FormFeedback/__tests__/__snapshots__/index.test.js.snap
  src/FormLabel/FormLabel.js.flow
  src/Heading/Heading.js
  src/Heading/Heading.js.flow
  src/Heading/__tests__/__snapshots__/index.test.js.snap
  src/Icon/index.js
  src/Radio/Radio.js
  src/Radio/Radio.js.flow
  src/Radio/__tests__/__snapshots__/index.test.js.snap
  src/Select/Select.js
  src/Select/Select.js.flow
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Text/Text.js
  src/Text/Text.js.flow
  src/Text/__tests__/__snapshots__/index.test.js.snap
  src/Text/consts.js
  src/TextLink/TextLink.js
  src/TextLink/TextLink.js.flow
  src/TextLink/__snapshots__/TextLink.stories.storyshot
  src/TextLink/__tests__/__snapshots__/index.test.js.snap
  src/Theming/ThemeProvider.js
  src/Theming/ThemeProvider.js.flow
  src/Theming/ThemeSwitcher.js
  src/Theming/ThemedSample.js
  src/Theming/Theming.stories.js
  src/Theming/__tests__/ThemedSample.test.js
  src/index.js
  yarn.lock
Labels: dependency, process/to-review, renovate

#250 ICONS: New and updated
  src/icons/icons.md
  src/icons/png/FlightDirect.png
  src/icons/png/FlightMulticity.png
  src/icons/png/FlightNomad.png
  src/icons/png/FlightReturn.png
  src/icons/png/GenderMan.png
  src/icons/png/GenderWoman.png
  src/icons/png/History.png
  src/icons/png/Trip.png
  src/icons/svg/flight-direct.svg
  src/icons/svg/flight-multicity.svg
  src/icons/svg/flight-nomad.svg
  src/icons/svg/flight-return.svg
  src/icons/svg/gender-man.svg
  src/icons/svg/gender-woman.svg
  src/icons/svg/globe.svg
  src/icons/svg/history.svg
  src/icons/svg/trip.svg
Labels: Icons

#248 FIX: Alert links and flex
  src/Alert/Alert.js
  src/Alert/Alert.stories.js
  src/Alert/__snapshots__/Alert.stories.storyshot
  src/Alert/__tests__/__snapshots__/index.test.js.snap
  src/Button/Button.js
  src/Button/__snapshots__/Button.stories.storyshot
  src/ButtonLink/ButtonLink.js
  src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/TextLink/TextLink.js
  src/TextLink/TextLink.js.flow
Labels: bug, process/to-review

#259 ICONS: New Moon, Sun, Sunrise
  src/icons/icons.md
  src/icons/png/Globe.png
  src/icons/png/Moon.png
  src/icons/png/Sun.png
  src/icons/png/Sunrise.png
  src/icons/svg/moon.svg
  src/icons/svg/sun.svg
  src/icons/svg/sunrise.svg
Labels: Icons

#206 NEW: InputField component
  src/InputField/InputField.js
  src/InputField/InputField.js.flow
  src/InputField/InputField.stories.js
  src/InputField/README.md
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputField/__tests__/__snapshots__/index.test.js.snap
  src/InputField/__tests__/index.test.js
  src/InputField/consts.js
  src/InputField/index.js
  src/InputField/index.js.flow
  src/TextLink/TextLink.js.flow
  src/index.js
  src/index.js.flow
Labels: New component, process/to-review

#271 ICONS: Fix Accomodation typo
  src/Icon/__tests__/__snapshots__/index.test.js.snap
  src/Icon/__tests__/index.test.js
  src/icons/icons.md
  src/icons/png/Accommodation.png
  src/icons/svg/accommodation.svg
Labels: Icons, process/to-review

#223 NEW: Textarea component
  src/Textarea/README.md
  src/Textarea/Textarea.js
  src/Textarea/Textarea.js.flow
  src/Textarea/Textarea.stories.js
  src/Textarea/__snapshots__/Textarea.stories.storyshot
  src/Textarea/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/__tests__/index.test.js
  src/Textarea/consts.js
  src/Textarea/index.js
  src/Textarea/index.js.flow
  src/index.js
  src/index.js.flow
Labels: New component, process/to-review
