Repository kiwicom/orbit, pull requests merged in 2018-09, with the labels that each got.

#340 ICONS: New & updated from Orbit UI 0.26.0
  src/Icon/__snapshots__/Icon.stories.storyshot
  src/icons/svg/airplane-down.svg
  src/icons/svg/airplane-return.svg
  src/icons/svg/airplane-right.svg
  src/icons/svg/airplane-up.svg
  src/icons/svg/gps-ios.svg
Labels: Icons

#341 Illustrations: New from Orbit UI 0.26.0
  src/Illustration/consts.js
  src/Illustration/index.js.flow
Labels: Illustrations, process/wip

#308 NEW: Loading component
  src/Alert/__snapshots__/Alert.stories.storyshot
  src/Button/Button.stories.js
  src/Button/__snapshots__/Button.stories.storyshot
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/Button/index.js
  src/Button/index.js.flow
  src/ButtonGroup/__snapshots__/ButtonGroup.stories.storyshot
  src/InputFile/__snapshots__/InputFile.stories.storyshot
  src/Loading/Loading.stories.js
  src/Loading/README.md
  src/Loading/__snapshots__/Loading.stories.storyshot
  src/Loading/__tests__/__snapshots__/index.test.js.snap
  src/Loading/__tests__/index.test.js
  src/Loading/consts.js
  src/Loading/index.js
  src/Loading/index.js.flow
  src/index.js
  src/index.js.flow
Labels: New component, process/to-review

#345 DOCS: Move theming to different folder
  .github/orbit-components.png
  .github/orbit-components@2x.png
  .github/theming.md
  readme.md
Labels: documentation

#347 FIX: README.md for Icons
  src/Icon/README.md
Labels: Icons, documentation

#297 NEW: Modal and Portal component
  .eslintrc
  src/ButtonLink/index.js.flow
  src/ClickOutside/README.md
  src/ClickOutside/__tests__/index.test.js
  src/ClickOutside/index.js
  src/ClickOutside/index.js.flow
  src/Heading/index.js
  src/Heading/index.js.flow
  src/Illustration/index.js
  src/List/index.js.flow
  src/Modal/Modal.stories.js
  src/Modal/ModalFooter/index.js
  src/Modal/ModalFooter/index.js.flow
  src/Modal/ModalHeader/index.js
  src/Modal/ModalHeader/index.js.flow
  src/Modal/ModalSection/index.js
  src/Modal/ModalSection/index.js.flow
  src/Modal/README.md
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Modal/__tests__/index.test.js
  src/Modal/consts.js
  src/Modal/index.js
  src/Modal/index.js.flow
  src/Portal/README.md
  src/Portal/__tests__/__snapshots__/index.test.js.snap
  src/Portal/__tests__/index.test.js
  src/Portal/index.js
  src/Portal/index.js.flow
  src/index.js
  src/index.js.flow
  src/utils/media.js
  src/utils/media.js.flow
Labels: New component, process/to-review

#358 UPDATE: ServiceLogo as suffix in Input
  src/Alert/Alert.stories.js
  src/Alert/__snapshots__/Alert.stories.storyshot
  src/InputField/InputField.stories.js
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputField/index.js
  src/InputGroup/__snapshots__/InputGroup.stories.storyshot
  src/ServiceLogo/index.js
  src/ServiceLogo/index.js.flow
Labels: process/requested-changes

#349 FIX: InputField z-index
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputField/index.js
  src/InputGroup/__snapshots__/InputGroup.stories.storyshot
  src/InputGroup/index.js
  src/Select/__snapshots__/Select.stories.storyshot
  src/Select/index.js
Labels: bug, process/to-review

#368 FIX: Modal scroll and height
  src/ClickOutside/index.js
  src/Modal/ModalHeader/index.js
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Modal/index.js
Labels: process/to-review

#369 FIX: Heading flow
  package.json
  src/Heading/index.js.flow
Labels: process/to-review

#378 ICONS: New & updated from Orbit UI 0.27.0
  src/Icon/__snapshots__/Icon.stories.storyshot
  src/icons/svg/invoice.svg
  src/icons/svg/money-transfer-in.svg
  src/icons/svg/money-transfer-out.svg
  src/icons/svg/partners.svg
  src/icons/svg/profit.svg
  src/icons/svg/refund.svg
  src/icons/svg/share-ios.svg
  src/icons/svg/share.svg
Labels: Icons, process/to-review

#385 FIX: href before external condition
  src/Button/index.js
  src/ButtonLink/index.js
Labels: bug, process/to-review

#388 UPDATE: Orbit-design-tokens version
  package.json
  src/Alert/__snapshots__/Alert.stories.storyshot
  src/Alert/__tests__/__snapshots__/index.test.js.snap
  src/Badge/__tests__/__snapshots__/index.test.js.snap
  src/Button/__snapshots__/Button.stories.storyshot
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/ButtonGroup/__snapshots__/ButtonGroup.stories.storyshot
  src/ButtonGroup/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  src/CountryFlag/__tests__/__snapshots__/index.test.js.snap
  src/FormFeedback/__tests__/__snapshots__/index.test.js.snap
  src/FormLabel/__tests__/__snapshots__/index.test.js.snap
  src/Heading/__tests__/__snapshots__/index.test.js.snap
  src/Illustration/__tests__/__snapshots__/index.test.js.snap
  src/InputField/__tests__/__snapshots__/index.test.js.snap
  src/InputFile/__snapshots__/InputFile.stories.storyshot
  src/InputFile/__tests__/__snapshots__/index.test.js.snap
  src/InputGroup/__tests__/__snapshots__/index.test.js.snap
  src/List/__tests__/__snapshots__/index.test.js.snap
  src/Loading/__snapshots__/Loading.stories.storyshot
  src/Loading/__tests__/__snapshots__/index.test.js.snap
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Radio/__tests__/__snapshots__/index.test.js.snap
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Separator/__tests__/__snapshots__/index.test.js.snap
  src/Text/__tests__/__snapshots__/index.test.js.snap
  src/TextLink/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/__tests__/__snapshots__/index.test.js.snap
  src/Tile/__tests__/__snapshots__/index.test.js.snap
  yarn.lock
Labels: process/to-review

#389 FIX: List ThemeProvider
  src/List/ListItem/index.js.flow
  src/List/__tests__/__snapshots__/index.test.js.snap
  src/List/index.js
  src/List/index.js.flow
Labels: process/to-review

#382 FIX: ListItem margin
  src/List/ListItem/index.js
  src/List/__snapshots__/List.stories.storyshot
Labels: process/to-review

#387 UPDATE: Add circled to Button, ButtonLink
  src/Button/Button.stories.js
  src/Button/README.md
  src/Button/__snapshots__/Button.stories.storyshot
  src/Button/index.js
  src/Button/index.js.flow
  src/ButtonLink/ButtonLink.stories.js
  src/ButtonLink/README.md
  src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
  src/ButtonLink/index.js
  src/ButtonLink/index.js.flow
Labels: process/to-review
