Repository kiwicom/orbit, pull requests merged in 2018-11, with the labels that each got.

#386 FIX: ModalFooter box-shadow, Close position
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Modal/index.js
  src/Modal/index.js.flow
Labels: Bug, Review needed

#494 NEW: TripSector and TripSegment component
  .loki/reference/chrome_iphone7_TripSector_Default.png
  .loki/reference/chrome_iphone7_TripSector_Multiple_days.png
  .loki/reference/chrome_iphone7_TripSector_Playground.png
  .loki/reference/chrome_iphone7_TripSegment_Default.png
  .loki/reference/chrome_iphone7_TripSegment_Playground.png
  .loki/reference/chrome_iphone7_TripSegment_Shown_by_default.png
  .loki/reference/chrome_laptop_Icon_List_of_all_icons.png
  .loki/reference/chrome_laptop_TripSector_Default.png
  .loki/reference/chrome_laptop_TripSector_Multiple_days.png
  .loki/reference/chrome_laptop_TripSector_Playground.png
  .loki/reference/chrome_laptop_TripSegment_Default.png
  .loki/reference/chrome_laptop_TripSegment_Playground.png
  .loki/reference/chrome_laptop_TripSegment_Shown_by_default.png
  src/CarrierLogo/index.js.flow
  src/List/ListItem/index.js.flow
  src/README.md
  src/TripSector/README.md
  src/TripSector/TripDate/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/TripDate/__tests__/index.test.js
  src/TripSector/TripDate/index.js
  src/TripSector/TripDate/index.js.flow
  src/TripSector/TripLayover/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/TripLayover/__tests__/index.test.js
  src/TripSector/TripLayover/index.js
  src/TripSector/TripLayover/index.js.flow
  src/TripSector/TripSector.stories.js
  src/TripSector/__snapshots__/TripSector.stories.storyshot
  src/TripSector/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/__tests__/index.test.js
  src/TripSector/index.js
  src/TripSector/index.js.flow
  src/TripSegment/README.md
  src/TripSegment/TripSegment.stories.js
  src/TripSegment/__snapshots__/TripSegment.stories.storyshot
  src/TripSegment/__tests__/__snapshots__/index.test.js.snap
  src/TripSegment/__tests__/index.test.js
  src/TripSegment/index.js
  src/TripSegment/index.js.flow
  src/index.js
  src/index.js.flow
  yarn.lock
Labels: Review needed

#539 UPDATE: React.Node for label in Radio and Checkbox
  src/Checkbox/Checkbox.stories.js
  src/Checkbox/__snapshots__/Checkbox.stories.storyshot
  src/Checkbox/index.js
  src/Checkbox/index.js.flow
  src/Radio/Radio.stories.js
  src/Radio/__snapshots__/Radio.stories.storyshot
  src/Radio/index.js
  src/Radio/index.js.flow
Labels: Enhancement

#401 UPDATE: Add forwarding ref to inputs
  package.json
  src/Checkbox/README.md
  src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/index.js
  src/Checkbox/index.js.flow
  src/InputField/README.md
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputField/__tests__/__snapshots__/index.test.js.snap
  src/InputField/index.js
  src/InputField/index.js.flow
  src/InputFile/README.md
  src/InputFile/__tests__/__snapshots__/index.test.js.snap
  src/InputFile/index.js
  src/InputFile/index.js.flow
  src/InputGroup/__snapshots__/InputGroup.stories.storyshot
  src/InputGroup/index.js
  src/InputStepper/README.md
  src/InputStepper/__snapshots__/InputStepper.stories.storyshot
  src/InputStepper/__tests__/__snapshots__/index.test.js.snap
  src/InputStepper/__tests__/index.test.js
  src/InputStepper/index.js
  src/InputStepper/index.js.flow
  src/Portal/__tests__/__snapshots__/index.test.js.snap
  src/Radio/README.md
  src/Radio/__tests__/__snapshots__/index.test.js.snap
  src/Radio/index.js
  src/Radio/index.js.flow
  src/Select/README.md
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Select/index.js
  src/Select/index.js.flow
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/Table/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/README.md
  src/Textarea/__snapshots__/Textarea.stories.storyshot
  src/Textarea/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/index.js
  src/common/common.js.flow
  yarn.lock
Labels: Review needed

#548 FIX: ButtonLink's size in ModalFooter
  src/Modal/Modal.stories.js
  src/Modal/ModalFooter/index.js
  src/Modal/__snapshots__/Modal.stories.storyshot
Labels: Bug, Review needed

#580 Update: orbit-design-tokens@0.2.3
  storybooknative/package.json
  storybooknative/src/Button/__tests__/__snapshots__/index.test.js.snap
  storybooknative/src/Text/__tests__/__snapshots__/index.test.js.snap
  storybooknative/yarn.lock
Labels: React Native

#582 RN Update: storybook v4
  storybooknative/.gitignore
  storybooknative/package.json
  storybooknative/yarn.lock
Labels: React Native

#541 UPDATE: orbit-design-tokens v0.2.3
  package.json
  src/Alert/__tests__/__snapshots__/index.test.js.snap
  src/Badge/__tests__/__snapshots__/index.test.js.snap
  src/Button/__snapshots__/Button.stories.storyshot
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/ButtonGroup/__snapshots__/ButtonGroup.stories.storyshot
  src/ButtonGroup/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  src/CountryFlag/__tests__/__snapshots__/index.test.js.snap
  src/FormFeedback/__tests__/__snapshots__/index.test.js.snap
  src/FormLabel/__tests__/__snapshots__/index.test.js.snap
  src/Heading/__tests__/__snapshots__/index.test.js.snap
  src/Icon/__tests__/__snapshots__/index.test.js.snap
  src/Illustration/__tests__/__snapshots__/index.test.js.snap
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputField/__tests__/__snapshots__/index.test.js.snap
  src/InputFile/__tests__/__snapshots__/index.test.js.snap
  src/InputGroup/__snapshots__/InputGroup.stories.storyshot
  src/InputGroup/__tests__/__snapshots__/index.test.js.snap
  src/InputStepper/__snapshots__/InputStepper.stories.storyshot
  src/InputStepper/__tests__/__snapshots__/index.test.js.snap
  src/List/__tests__/__snapshots__/index.test.js.snap
  src/Loading/__tests__/__snapshots__/index.test.js.snap
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Radio/__tests__/__snapshots__/index.test.js.snap
  src/RatingStars/__tests__/__snapshots__/index.test.js.snap
  src/Select/__snapshots__/Select.stories.storyshot
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Separator/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/StopoverArrow/__tests__/__snapshots__/index.test.js.snap
  src/Table/__tests__/__snapshots__/index.test.js.snap
  src/Text/__tests__/__snapshots__/index.test.js.snap
  src/TextLink/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/__snapshots__/Textarea.stories.storyshot
  src/Textarea/__tests__/__snapshots__/index.test.js.snap
  src/Tile/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/TripDate/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/TripLayover/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/__tests__/__snapshots__/index.test.js.snap
  src/TripSegment/__tests__/__snapshots__/index.test.js.snap
  yarn.lock
Labels: Review needed

#544 FIX: Modal scroll handler
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Modal/index.js
Labels: Bug

#550 RN: New simple card component
  storybooknative/src/Card/Card.stories.js
  storybooknative/src/Card/__tests__/__snapshots__/index.test.js.snap
  storybooknative/src/Card/__tests__/index.test.js
  storybooknative/src/Card/index.js
  storybooknative/src/Card/index.js.flow
  storybooknative/src/styled/__tests__/index.test.js
  storybooknative/src/styled/index.js
  storybooknative/src/types/Style.js
  storybooknative/storybook/story-loader.js
Labels: React Native

#600 UPDATE: Flow to 0.81
  flow-typed/npm/styled-components_v3.x.x.js
  package.json
  src/Button/index.js.flow
  src/ButtonLink/index.js.flow
  src/Card/CardHeader/index.js.flow
  src/Card/CardSection/index.js.flow
  src/CarrierLogo/index.js.flow
  src/Heading/index.js.flow
  src/InputField/index.js.flow
  src/List/ListItem/index.js.flow
  src/Loading/index.js.flow
  src/Modal/ModalFooter/index.js.flow
  src/Modal/ModalHeader/index.js.flow
  src/Modal/ModalSection/index.js.flow
  src/Select/index.js.flow
  src/ServiceLogo/index.js.flow
  src/Table/TableBody/index.js.flow
  src/Table/TableCell/index.js.flow
  src/Table/TableRow/index.js.flow
  src/Text/index.js.flow
  src/TextLink/index.js.flow
  src/Tile/TileHeader/index.js.flow
  src/TripSegment/index.js.flow
  yarn.lock
Labels: ASAP, Review needed

#598 Chore/sync react native with master
  package.json
  src/Alert/__tests__/__snapshots__/index.test.js.snap
  src/Badge/__tests__/__snapshots__/index.test.js.snap
  src/Badge/index.js
  src/Button/__snapshots__/Button.stories.storyshot
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/ButtonGroup/__snapshots__/ButtonGroup.stories.storyshot
  src/ButtonGroup/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  src/CountryFlag/__tests__/__snapshots__/index.test.js.snap
  src/FormFeedback/__tests__/__snapshots__/index.test.js.snap
  src/FormLabel/__tests__/__snapshots__/index.test.js.snap
  src/Heading/__tests__/__snapshots__/index.test.js.snap
  src/Icon/__tests__/__snapshots__/index.test.js.snap
  src/Illustration/__tests__/__snapshots__/index.test.js.snap
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputField/__tests__/__snapshots__/index.test.js.snap
  src/InputFile/__tests__/__snapshots__/index.test.js.snap
  src/InputGroup/__snapshots__/InputGroup.stories.storyshot
  src/InputGroup/__tests__/__snapshots__/index.test.js.snap
  src/InputStepper/__snapshots__/InputStepper.stories.storyshot
  src/InputStepper/__tests__/__snapshots__/index.test.js.snap
  src/List/__tests__/__snapshots__/index.test.js.snap
  src/Loading/__tests__/__snapshots__/index.test.js.snap
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Modal/index.js
  src/Portal/index.js
  src/Radio/__tests__/__snapshots__/index.test.js.snap
  src/RatingStars/__tests__/__snapshots__/index.test.js.snap
  src/Select/__snapshots__/Select.stories.storyshot
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Select/index.js
  src/Separator/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/StopoverArrow/__tests__/__snapshots__/index.test.js.snap
  src/Table/__tests__/__snapshots__/index.test.js.snap
  src/Text/__tests__/__snapshots__/index.test.js.snap
  src/TextLink/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/__snapshots__/Textarea.stories.storyshot
  src/Textarea/__tests__/__snapshots__/index.test.js.snap
  src/Tile/Tile.stories.js
  src/Tile/TileHeader/index.js.flow
  src/Tile/__snapshots__/Tile.stories.storyshot
  src/Tile/__tests__/__snapshots__/index.test.js.snap
  src/Tile/index.js.flow
  src/TripSector/TripDate/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/TripLayover/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/__snapshots__/TripSector.stories.storyshot
  src/TripSector/__tests__/__snapshots__/index.test.js.snap
  src/TripSegment/__snapshots__/TripSegment.stories.storyshot
  src/TripSegment/__tests__/__snapshots__/index.test.js.snap
  src/TripSegment/index.js
  yarn.lock
Labels: React Native

#604 UPDATE: Flow 0.85
  package.json
  src/InputField/index.js
  src/Modal/ModalHeader/index.js
  src/Tile/index.js
  yarn.lock
Labels: Review needed

#605 DEV: Update orbit-design-tokens to 0.2.5
  package.json
  yarn.lock
Labels: Review needed

#607 FIX: Card docs
  src/Card/README.md
Labels: Documentation

#584 Add: README + create-new-component script
  storybooknative/README.md
  storybooknative/package.json
  storybooknative/scripts/create-new-component.js
Labels: React Native

#624 FIX: Clear timeout in TileExpandable
  src/Tile/TileExpandable/index.js
Labels: Review needed

#628 FIX: Copying flow files in build
  package.json
Labels: ASAP

#632 FIX: InputField docs
  src/InputField/README.md
Labels: Documentation

#489 UPDATE: Stack
  src/Alert/__snapshots__/Alert.stories.storyshot
  src/Card/__snapshots__/Card.stories.storyshot
  src/Card/index.js
  src/Checkbox/__snapshots__/Checkbox.stories.storyshot
  src/Checkbox/index.js
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputField/index.js
  src/InputFile/__snapshots__/InputFile.stories.storyshot
  src/InputFile/index.js
  src/InputGroup/__snapshots__/InputGroup.stories.storyshot
  src/InputGroup/index.js
  src/InputStepper/__snapshots__/InputStepper.stories.storyshot
  src/InputStepper/__tests__/__snapshots__/index.test.js.snap
  src/InputStepper/index.js
  src/Loading/__snapshots__/Loading.stories.storyshot
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Radio/__snapshots__/Radio.stories.storyshot
  src/Radio/index.js
  src/Select/__snapshots__/Select.stories.storyshot
  src/Select/index.js
  src/Stack/README.md
  src/Stack/Stack.stories.js
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__tests__/index.test.js
  src/Stack/consts.js
  src/Stack/index.js
  src/Stack/index.js.flow
  src/Table/__snapshots__/Table.stories.storyshot
  src/Table/index.js
  src/Tile/Tile.stories.js
  src/Tile/__snapshots__/Tile.stories.storyshot
  src/Tile/index.js
  src/_deprecated/Card/__snapshots__/Card.stories.storyshot
Labels: Review needed

#638 FIX: InputField password visibility in IE
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputField/index.js
  src/InputGroup/__snapshots__/InputGroup.stories.storyshot
  src/InputStepper/__snapshots__/InputStepper.stories.storyshot
  src/InputStepper/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/Stack/__tests__/__snapshots__/index.test.js.snap
Labels: Bug, Review needed

#655 FIX: TripSector height
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/TripSector/__snapshots__/TripSector.stories.storyshot
  src/TripSector/index.js
Labels: Bug, Review needed

#645 FIX: Modal dataTest docs
  src/Modal/README.md
Labels: Documentation

#656 FIX: TripSegment CarrierLogo
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/TripSector/__snapshots__/TripSector.stories.storyshot
  src/TripSegment/__snapshots__/TripSegment.stories.storyshot
  src/TripSegment/index.js
Labels: Bug, Review needed

#665 UPDATE: Add dataTest to Stack
  src/Stack/README.md
  src/Stack/Stack.stories.js
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__tests__/index.test.js
  src/Stack/index.js
  src/Stack/index.js.flow
Labels: Review needed

#666 FIX: Checkbox flow type
  src/Checkbox/index.js.flow
Labels: Review needed

#668 ADD: Heading type title5
  src/Card/__snapshots__/Card.stories.storyshot
  src/Heading/Heading.stories.js
  src/Heading/README.md
  src/Heading/__snapshots__/Heading.stories.storyshot
  src/Heading/__tests__/__snapshots__/index.test.js.snap
  src/Heading/__tests__/index.test.js
  src/Heading/consts.js
  src/Heading/index.js
  src/Heading/index.js.flow
  src/ListChoice/__snapshots__/ListChoice.stories.storyshot
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/Tile/__snapshots__/Tile.stories.storyshot
  src/_deprecated/Card/__snapshots__/Card.stories.storyshot
Labels: Review needed

#662 UPDATE: Compact InputField font-weight
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputField/index.js
  src/InputGroup/__snapshots__/InputGroup.stories.storyshot
  src/InputStepper/__snapshots__/InputStepper.stories.storyshot
  src/InputStepper/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/Stack/__tests__/__snapshots__/index.test.js.snap
Labels: Review needed

#669 UPDATE: StopoverArrow glyphs and number of stops
  src/Stack/Stack.stories.js
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/StopoverArrow/README.md
  src/StopoverArrow/__snapshots__/StopoverArrow.stories.storyshot
  src/StopoverArrow/__tests__/__snapshots__/index.test.js.snap
  src/StopoverArrow/__tests__/index.test.js
  src/StopoverArrow/consts.js
  src/StopoverArrow/index.js
  src/StopoverArrow/index.js.flow
Labels: Review needed
