Repository kiwicom/orbit, pull requests merged in 2018-10, with the labels that each got.

#399 FIX: Icon theming
  config/jestSetupFramework.js
  flow-typed/npm/jest-styled-components_vx.x.x.js
  flow-typed/npm/jest_v22.x.x.js
  flow-typed/npm/jest_v23.x.x.js
  flow-typed/npm/jest_vx.x.x.js
  jest.json
  package.json
  src/Alert/__snapshots__/Alert.stories.storyshot
  src/Badge/__snapshots__/Badge.stories.storyshot
  src/Button/__snapshots__/Button.stories.storyshot
  src/ButtonGroup/__snapshots__/ButtonGroup.stories.storyshot
  src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/Card/__snapshots__/Card.stories.storyshot
  src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/__snapshots__/Checkbox.stories.storyshot
  src/FormLabel/__tests__/__snapshots__/index.test.js.snap
  src/Icon/Icon.stories.js
  src/Icon/__snapshots__/Icon.stories.storyshot
  src/Icon/__tests__/__snapshots__/index.test.js.snap
  src/Icon/__tests__/index.test.js
  src/Icon/consts.js
  src/Icon/index.js
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputFile/__snapshots__/InputFile.stories.storyshot
  src/InputGroup/__snapshots__/InputGroup.stories.storyshot
  src/List/__snapshots__/List.stories.storyshot
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Select/__snapshots__/Select.stories.storyshot
  src/ServiceLogo/__tests__/__snapshots__/index.test.js.snap
  src/TextLink/__snapshots__/TextLink.stories.storyshot
  src/Tile/__snapshots__/Tile.stories.storyshot
  yarn.lock
Labels: Icons, process/to-review

#403 FIX: Textarea ThemeProvider
  src/Textarea/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/consts.js
  src/Textarea/index.js
  src/Textarea/index.js.flow
Labels: process/to-review

#404 FIX: Heading ThemeProvider
  src/Heading/__tests__/__snapshots__/index.test.js.snap
  src/Heading/consts.js
  src/Heading/index.js
  src/Heading/index.js.flow
Labels: process/to-review

#402 FIX: Illustration ThemeProvider
  src/Illustration/__tests__/__snapshots__/index.test.js.snap
  src/Illustration/__tests__/index.test.js
  src/Illustration/index.js
Labels: process/to-review

#405 FIX: Checkbox ThemeProvider
  src/Checkbox/__snapshots__/Checkbox.stories.storyshot
  src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/consts.js
  src/Checkbox/index.js
  src/Checkbox/index.js.flow
  src/Radio/index.js
Labels: process/to-review

#411 FIX: CheckBox DOM rendering
  src/Checkbox/__snapshots__/Checkbox.stories.storyshot
  src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/index.js
Labels: process/to-review

#406 FIX: InputGroup ThemeProvider
  src/InputGroup/InputGroup.stories.js
  src/InputGroup/__tests__/__snapshots__/index.test.js.snap
  src/InputGroup/consts.js
  src/InputGroup/index.js
  src/InputGroup/index.js.flow
Labels: process/to-review

#421 UPDATE: orbit-design-tokens
  package.json
  yarn.lock
Labels: process/to-review

#410 UPDATE: Add submit to Button, ButtonLink
  src/Alert/__snapshots__/Alert.stories.storyshot
  src/Button/Button.stories.js
  src/Button/README.md
  src/Button/__snapshots__/Button.stories.storyshot
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/Button/__tests__/index.test.js
  src/Button/index.js
  src/Button/index.js.flow
  src/ButtonGroup/__snapshots__/ButtonGroup.stories.storyshot
  src/ButtonLink/ButtonLink.stories.js
  src/ButtonLink/README.md
  src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/__tests__/index.test.js
  src/ButtonLink/index.js
  src/ButtonLink/index.js.flow
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputFile/__snapshots__/InputFile.stories.storyshot
  src/Loading/__snapshots__/Loading.stories.storyshot
  src/Modal/__snapshots__/Modal.stories.storyshot
Labels: process/to-review

#355 NEW: Table component
  src/Table/Table.stories.js
  src/Table/TableBody/index.js
  src/Table/TableBody/index.js.flow
  src/Table/TableCell/index.js
  src/Table/TableCell/index.js.flow
  src/Table/TableHead/index.js
  src/Table/TableHead/index.js.flow
  src/Table/TableRow/index.js
  src/Table/TableRow/index.js.flow
  src/Table/__snapshots__/Table.stories.storyshot
  src/Table/__tests__/__snapshots__/index.test.js.snap
  src/Table/__tests__/index.test.js
  src/Table/index.js
  src/Table/index.js.flow
  src/index.js
  src/index.js.flow
Labels: New component, process/to-review

#429 FIX: Table flow and README
  src/Table/README.md
  src/Table/TableBody/index.js.flow
  src/Table/TableHead/index.js.flow
  src/Table/TableRow/index.js.flow
  src/Table/index.js.flow
Labels: process/to-review

#430 FIX: Button, ButtonLink icon size
  src/Button/__snapshots__/Button.stories.storyshot
  src/Button/index.js
  src/ButtonGroup/__snapshots__/ButtonGroup.stories.storyshot
  src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/index.js
  src/Icon/index.js
  src/Icon/index.js.flow
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputFile/__snapshots__/InputFile.stories.storyshot
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Stack/__snapshots__/Stack.stories.storyshot
Labels: process/to-review

#433 React Native Web integration: possible to see react-native components…
  storybooknative/.storybook/README.md
  storybooknative/.storybook/addons.js
  storybooknative/.storybook/config.js
  storybooknative/.storybook/webpack.config.js
  storybooknative/helpers/storiesOf/index.android.js
  storybooknative/helpers/storiesOf/index.ios.js
  storybooknative/helpers/storiesOf/index.js
  storybooknative/package.json
  storybooknative/public/favicon.ico
  storybooknative/public/index.html
  storybooknative/public/manifest.json
  storybooknative/src/Button/index.js
  storybooknative/storybook/stories/index.js
  storybooknative/yarn.lock
Labels: react-native

#438 Wrap styled and use flow to validate styles passed to styled
  storybooknative/src/CenterView/index.js
  storybooknative/src/styled/index.js
  storybooknative/src/types/StylesPropType.js
Labels: react-native

#440 Fix: babel-core version updated to 7.0.0-bridge.0
  storybooknative/package.json
  storybooknative/yarn.lock
Labels: process/to-review, react-native

#442 React Native: Fetching stories like in original setup
  .eslintignore
  .flowconfig
  storybooknative/.storybook/config.js
  storybooknative/package.json
  storybooknative/src/Button/Button.stories.js
  storybooknative/src/Welcome/Welcome.stories.js
  storybooknative/storybook/story-loader.js
  storybooknative/storybook/storybook.js
  storybooknative/yarn.lock
Labels: process/wip, react-native

#448 ICONS: Orbit UI 0.28.0
  src/Icon/__snapshots__/Icon.stories.storyshot
  src/icons/svg/lock-open.svg
  src/icons/svg/lock.svg
Labels: Icons, process/to-review

#450 FIX: Select and InputFile help/error position
  src/InputFile/__snapshots__/InputFile.stories.storyshot
  src/InputFile/index.js
  src/InputGroup/__snapshots__/InputGroup.stories.storyshot
  src/Select/Select.stories.js
  src/Select/__snapshots__/Select.stories.storyshot
  src/Select/index.js
Labels: bug, process/to-review

#453 FIX: Modal closing
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Modal/index.js
  src/Modal/index.js.flow
Labels: bug, process/to-review

#451 FIX: ModalFooter conditional expression
  src/Modal/Modal.stories.js
  src/Modal/ModalFooter/index.js
Labels: bug, process/to-review

#479 FIX: Illustration flow type - theme
  src/Illustration/index.js.flow
Labels: process/to-review

#478 FIX: Loading theming
  src/Loading/Loading.stories.js
  src/Loading/__tests__/__snapshots__/index.test.js.snap
  src/Loading/__tests__/index.test.js
  src/Loading/consts.js
  src/Loading/index.js
Labels: process/to-review

#470 FIX: Multi-line FormFeedback
  src/FormFeedback/index.js
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputFile/__snapshots__/InputFile.stories.storyshot
  src/Select/__snapshots__/Select.stories.storyshot
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/__snapshots__/Textarea.stories.storyshot
Labels: bug, process/to-review

#354 NEW: Tile expandable option
  src/Tile/README.md
  src/Tile/Tile.stories.js
  src/Tile/TileExpandable/index.js
  src/Tile/TileExpandable/index.js.flow
  src/Tile/TileHeader/index.js
  src/Tile/TileHeader/index.js.flow
  src/Tile/__snapshots__/Tile.stories.storyshot
  src/Tile/__tests__/__snapshots__/index.test.js.snap
  src/Tile/__tests__/index.test.js
  src/Tile/index.js
  src/Tile/index.js.flow
  src/utils/toggleDown/index.js
  src/utils/toggleDown/index.js.flow
  src/utils/toggleUp/index.js
  src/utils/toggleUp/index.js.flow
Labels: New component, process/to-review

#426 FIX: Modal height on desktop
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Modal/index.js
Labels: bug, process/to-review

#454 FIX: Stack align-items
  src/Stack/Stack.stories.js
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__tests__/index.test.js
  src/Stack/index.js
  src/index.js.flow
Labels: process/to-review

#475 FIX: IE - Loading Button
  src/Loading/__snapshots__/Loading.stories.storyshot
  src/Loading/index.js
Labels: bug, process/to-review

#456 FIX: Icons size in stories
  src/Button/index.js
  src/ButtonLink/index.js
  src/Icon/Icon.stories.js
  src/Icon/__snapshots__/Icon.stories.storyshot
  src/Icon/index.js
  src/Icon/index.js.flow
Labels: process/to-review

#483 ADD: Staging
  .circleci/config.yml
  .gitignore
  config/deploymentUtils.js
  package.json
  yarn.lock
Labels: process/to-review

#471 Text component
  jest.json
  package.json
  storybooknative/.babelrc
  storybooknative/.flowconfig
  storybooknative/.storybook/addons.js
  storybooknative/babel.config.js.bak
  storybooknative/package.json
  storybooknative/scripts/test.sh
  storybooknative/src/Button/index.android.js
  storybooknative/src/Button/index.ios.js
  storybooknative/src/Text/Text.stories.js
  storybooknative/src/Text/__tests__/__snapshots__/index.test.js.snap
  storybooknative/src/Text/__tests__/index.test.js
  storybooknative/src/Text/consts.js
  storybooknative/src/Text/index.js
  storybooknative/src/Text/index.js.flow
  storybooknative/src/Welcome/Welcome.stories.js
  storybooknative/src/defaultTokens.js
  storybooknative/src/styled/index.js
  storybooknative/storybook/addons.js
  storybooknative/storybook/story-loader.js
  storybooknative/yarn.lock
  yarn.lock
Labels: react-native

#487 FIX: ListItem icon align
  src/List/List.stories.js
  src/List/ListItem/index.js
  src/List/ListItem/index.js.flow
  src/List/__snapshots__/List.stories.storyshot
  src/List/index.js
Labels: process/to-review

#492 FIX: InputFile CloseButton triggers file selection
  src/InputFile/__tests__/__snapshots__/index.test.js.snap
  src/InputFile/__tests__/index.test.js
  src/InputFile/index.js
  src/InputFile/index.js.flow
Labels: bug

#493 FIX: InputGroup without label
  src/InputGroup/InputGroup.stories.js
  src/InputGroup/__snapshots__/InputGroup.stories.storyshot
  src/InputGroup/index.js
Labels: bug

#427 FIX: Select placeholder - selected attribute
  src/InputGroup/__snapshots__/InputGroup.stories.storyshot
  src/Select/Select.stories.js
  src/Select/__snapshots__/Select.stories.storyshot
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Select/index.js
Labels: bug, process/to-review

#506 UPDATE: Optional label in Radio and Checkbox
  src/Checkbox/README.md
  src/Checkbox/index.js.flow
  src/Radio/README.md
  src/Radio/index.js.flow
Labels: process/to-review

#422 FIX: Portal SSR
  src/Portal/index.js
Labels: bug, process/to-review

#490 FIX: Modal absolute content overflow
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Modal/index.js
Labels: bug

#502 FIX: Radio and Checkbox label height
  src/Checkbox/__snapshots__/Checkbox.stories.storyshot
  src/Checkbox/index.js
  src/Radio/__snapshots__/Radio.stories.storyshot
  src/Radio/index.js
Labels: bug, process/to-review

#491 FIX: Tile icon shrink
  src/Tile/TileHeader/index.js
  src/Tile/__snapshots__/Tile.stories.storyshot
Labels: bug

#503 FIX: List and Text color in Alert
  src/Alert/Alert.stories.js
  src/Alert/__snapshots__/Alert.stories.storyshot
  src/Alert/index.js
  src/List/ListItem/index.js.flow
  src/Text/index.js
  src/Text/index.js.flow
Labels: process/to-review

#504 UPDATE: Textarea fullHeight prop
  src/Textarea/README.md
  src/Textarea/Textarea.stories.js
  src/Textarea/__snapshots__/Textarea.stories.storyshot
  src/Textarea/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/__tests__/index.test.js
  src/Textarea/index.js
  src/Textarea/index.js.flow
Labels: enhancement, process/to-review

#508 React-native - TextInput code extracted from kiwi/mobile
  storybooknative/src/InputField/index.js
Labels: react-native

#505 DEV: Update orbit-design-tokens
  package.json
  src/Alert/__snapshots__/Alert.stories.storyshot
  src/Alert/__tests__/__snapshots__/index.test.js.snap
  src/Badge/__tests__/__snapshots__/index.test.js.snap
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/ButtonGroup/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  src/CountryFlag/__tests__/__snapshots__/index.test.js.snap
  src/FormFeedback/__tests__/__snapshots__/index.test.js.snap
  src/FormLabel/__tests__/__snapshots__/index.test.js.snap
  src/Heading/__tests__/__snapshots__/index.test.js.snap
  src/Icon/__tests__/__snapshots__/index.test.js.snap
  src/Illustration/__tests__/__snapshots__/index.test.js.snap
  src/InputField/__tests__/__snapshots__/index.test.js.snap
  src/InputFile/__tests__/__snapshots__/index.test.js.snap
  src/InputGroup/__tests__/__snapshots__/index.test.js.snap
  src/List/__tests__/__snapshots__/index.test.js.snap
  src/Loading/__tests__/__snapshots__/index.test.js.snap
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Radio/__tests__/__snapshots__/index.test.js.snap
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Separator/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/Table/__tests__/__snapshots__/index.test.js.snap
  src/Text/__tests__/__snapshots__/index.test.js.snap
  src/TextLink/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/__tests__/__snapshots__/index.test.js.snap
  src/Tile/__tests__/__snapshots__/index.test.js.snap
  yarn.lock
Labels: process/to-review

#514 Basic Input structure
  storybooknative/src/InputField/InputField.stories.js
  storybooknative/src/InputField/consts.js
  storybooknative/src/InputField/index.js
  storybooknative/src/InputField/index.js.flow
  storybooknative/storybook/story-loader.js
Labels: react-native

#443 NEW: RatingStars component
  src/Icon/index.js.flow
  src/RatingStars/README.md
  src/RatingStars/RatingStars.stories.js
  src/RatingStars/__snapshots__/RatingStars.stories.storyshot
  src/RatingStars/__tests__/__snapshots__/index.test.js.snap
  src/RatingStars/__tests__/index.test.js
  src/RatingStars/consts.js
  src/RatingStars/index.js
  src/RatingStars/index.js.flow
  src/index.js
  src/index.js.flow
Labels: New component, process/to-review

#520 FIX: CarrierLogo rendered size
  src/CarrierLogo/__snapshots__/CarrierLogo.stories.storyshot
  src/CarrierLogo/index.js
  src/List/__snapshots__/List.stories.storyshot
Labels: bug

#519 Label styles + inline label prop
  storybooknative/src/CenterView/index.js
  storybooknative/src/FormLabel/index.js
  storybooknative/src/FormLabel/index.js.flow
  storybooknative/src/InputField/InputField.stories.js
  storybooknative/src/InputField/index.js
  storybooknative/src/Types.js
Labels: react-native

#521 Error and help messages.
  storybooknative/src/CenterView/index.js
  storybooknative/src/FormFeedback/consts.js
  storybooknative/src/FormFeedback/index.js
  storybooknative/src/FormFeedback/index.js.flow
  storybooknative/src/FormLabel/index.js.flow
  storybooknative/src/InputField/InputField.stories.js
  storybooknative/src/InputField/index.js
  storybooknative/src/InputField/index.js.flow
Labels: react-native

#441 NEW: StopoverArrow component
  .loki/reference/chrome_iphone7_StopoverArrow_Playground.png
  .loki/reference/chrome_laptop_StopoverArrow_Playground.png
  src/StopoverArrow/README.md
  src/StopoverArrow/StopoverArrow.stories.js
  src/StopoverArrow/__snapshots__/StopoverArrow.stories.storyshot
  src/StopoverArrow/__tests__/__snapshots__/index.test.js.snap
  src/StopoverArrow/__tests__/index.test.js
  src/StopoverArrow/consts.js
  src/StopoverArrow/index.js
  src/StopoverArrow/index.js.flow
  src/index.js
  src/index.js.flow
Labels: New component, process/to-review

#480 FIX: Modal width
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Modal/index.js
Labels: bug, process/to-review

#525 FIX: Stack spaceAfter docs
  src/Stack/README.md
Labels: documentation

#529 FIX: CardSection subTitle render
  src/Card/CardSection/index.js
  src/Card/__snapshots__/Card.stories.storyshot
Labels: ASAP

#524 Focused state
  storybooknative/src/InputField/InputField.stories.js
  storybooknative/src/InputField/index.js
Labels: react-native

#538 UPDATE: Stack spacing documentation
  src/Stack/README.md
Labels: documentation

#537 UDATE: storybooknative .gitignore
  storybooknative/.gitignore
Labels: react-native

#534 FIX: Section without CardHeader
  .loki/reference/chrome_iphone7_Card_Card_with_expandable_sections.png
  .loki/reference/chrome_iphone7_Card_Card_with_mixed_sections.png
  .loki/reference/chrome_iphone7_Card_Card_with_sections.png
  .loki/reference/chrome_laptop_Card_Card_with_expandable_sections.png
  .loki/reference/chrome_laptop_Card_Card_with_mixed_sections.png
  .loki/reference/chrome_laptop_Card_Card_with_sections.png
  src/Card/Card.stories.js
  src/Card/__snapshots__/Card.stories.storyshot
  src/Card/index.js
Labels: review-needed

#567 Remove unnecessary style typeing
  storybooknative/src/Button/index.js
  storybooknative/src/CenterView/index.js
  storybooknative/src/Touchable/index.js
Labels: React Native

#569 FIX: White Badge color
  src/Badge/__snapshots__/Badge.stories.storyshot
  src/Badge/index.js
Labels: Bug, Review needed
