Repository kiwicom/orbit, pull requests merged in 2018-06, with the labels that each got.

#205 Give a value to textarea via prop
  src/_deprecated/InputTextarea/InputTextarea.js
  src/_deprecated/InputTextarea/__snapshots__/InputTextarea.stories.storyshot
Labels: bug

#186 Add new ButtonLink component
  src/Alert/Alert.js
  src/Alert/Alert.stories.js
  src/Alert/__snapshots__/Alert.stories.storyshot
  src/Alert/__tests__/__snapshots__/index.test.js.snap
  src/Alert/__tests__/index.test.js
  src/Alert/index.js
  src/ButtonLink/ButtonLink.js
  src/ButtonLink/ButtonLink.stories.js
  src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/__tests__/index.test.js
  src/ButtonLink/index.js
  src/index.js
Labels: process/to-review

#213 Separate withTheme from Heading component
  src/Heading/Heading.js
  src/Heading/Heading.stories.js
  src/Heading/__snapshots__/Heading.stories.storyshot
  src/Heading/__tests__/__snapshots__/index.test.js.snap
  src/Heading/__tests__/index.test.js
  src/Heading/index.js
Labels: process/to-review

#183 Update TextLink support Theming
  src/TextLink/TextLink.js
  src/TextLink/TextLink.stories.js
  src/TextLink/__snapshots__/TextLink.stories.storyshot
  src/TextLink/__tests__/__snapshots__/index.test.js.snap
  src/TextLink/__tests__/index.test.js
  src/TextLink/index.js
Labels: process/to-review

#214 Separate withTheme from Button component
  src/Button/Button.js
  src/Button/Button.stories.js
  src/Button/__snapshots__/Button.stories.storyshot
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/Button/__tests__/index.test.js
  src/Button/index.js
Labels: process/to-review

#216 Update Alert component
  src/Alert/Alert.js
  src/Alert/__snapshots__/Alert.stories.storyshot
  src/Alert/__tests__/__snapshots__/index.test.js.snap
Labels: process/to-review

#182 Update Text support Theming
  src/Text/Text.js
  src/Text/Text.stories.js
  src/Text/__snapshots__/Text.stories.storyshot
  src/Text/__tests__/__snapshots__/index.test.js.snap
  src/Text/__tests__/index.test.js
  src/Text/index.js
Labels: process/to-review

#229 NEW: BaggageStorage icon
  src/icons/icons.md
  src/icons/png/BaggageStorage.png
  src/icons/svg/baggage-storage.svg
Labels: ASAP

#230 FIX: Text component index flow
  src/Text/index.js.flow
Labels: process/to-review

#184 Update CarrierLogo support Theming
  src/CarrierLogo/CarrierLogo.js
  src/CarrierLogo/CarrierLogo.js.flow
  src/CarrierLogo/CarrierLogo.stories.js
  src/CarrierLogo/__snapshots__/CarrierLogo.stories.storyshot
  src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
  src/CarrierLogo/__tests__/index.test.js
  src/CarrierLogo/consts.js
  src/CarrierLogo/index.js
  src/CarrierLogo/index.js.flow
Labels: process/to-review

#180 Add new Card component
  src/Card/Card.js
  src/Card/Card.js.flow
  src/Card/Card.stories.js
  src/Card/CardContent/CardContent.js
  src/Card/CardContent/CardContent.js.flow
  src/Card/CardContent/index.js
  src/Card/CardContent/index.js.flow
  src/Card/CardHeader/CardHeader.js
  src/Card/CardHeader/CardHeader.js.flow
  src/Card/CardHeader/index.js
  src/Card/CardHeader/index.js.flow
  src/Card/CardSection/CardSection.js
  src/Card/CardSection/CardSection.js.flow
  src/Card/CardSection/index.js
  src/Card/CardSection/index.js.flow
  src/Card/__snapshots__/Card.stories.storyshot
  src/Card/__tests__/index.test.js
  src/Card/index.js
  src/Card/index.js.flow
  src/index.js
  src/index.js.flow
Labels: process/to-review
