Repository kiwicom/orbit, pull requests merged in 2018-08, with the labels that each got.

#215 ICONS: Change build config
  config/build.js
  package.json
  readme.md
  src/Icon/README.md
  src/Icon/__snapshots__/Icon.stories.storyshot
  src/Icon/consts.js
  src/Icon/index.js.flow
  yarn.lock
Labels: Icons, process/to-review

#289 FIX: Textarea value prop
  src/Textarea/README.md
  src/Textarea/Textarea.stories.js
  src/Textarea/__snapshots__/Textarea.stories.storyshot
  src/Textarea/__tests__/index.test.js
  src/Textarea/index.js
  src/Textarea/index.js.flow
Labels: process/to-review

#225 NEW: ButtonGroup component
  src/Button/index.js
  src/Button/index.js.flow
  src/ButtonGroup/ButtonGroup.stories.js
  src/ButtonGroup/README.md
  src/ButtonGroup/__snapshots__/ButtonGroup.stories.storyshot
  src/ButtonGroup/__tests__/__snapshots__/index.test.js.snap
  src/ButtonGroup/__tests__/index.test.js
  src/ButtonGroup/index.js
  src/ButtonGroup/index.js.flow
  src/ButtonLink/index.js
  src/ButtonLink/index.js.flow
  src/index.js
  src/index.js.flow
Labels: New component, process/to-review

#243 NEW: Badge component
  src/Badge/Badge.stories.js
  src/Badge/README.md
  src/Badge/__snapshots__/Badge.stories.storyshot
  src/Badge/__tests__/__snapshots__/index.test.js.snap
  src/Badge/__tests__/index.test.js
  src/Badge/consts.js
  src/Badge/index.js
  src/Badge/index.js.flow
  src/index.js
  src/index.js.flow
Labels: New component, process/to-review

#294 UPDATE: Textarea resize
  src/Textarea/README.md
  src/Textarea/Textarea.stories.js
  src/Textarea/__snapshots__/Textarea.stories.storyshot
  src/Textarea/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/__tests__/index.test.js
  src/Textarea/consts.js
  src/Textarea/index.js
  src/Textarea/index.js.flow
Labels: process/to-review

#244 UPDATE: iconRight for Buttons
  src/Alert/__snapshots__/Alert.stories.storyshot
  src/Button/Button.stories.js
  src/Button/README.md
  src/Button/__snapshots__/Button.stories.storyshot
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/Button/__tests__/index.test.js
  src/Button/index.js
  src/Button/index.js.flow
  src/ButtonGroup/__snapshots__/ButtonGroup.stories.storyshot
  src/ButtonLink/ButtonLink.stories.js
  src/ButtonLink/README.md
  src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/__tests__/index.test.js
  src/ButtonLink/index.js
  src/ButtonLink/index.js.flow
  src/InputField/__snapshots__/InputField.stories.storyshot
Labels: enhancement, process/to-review

#246 NEW: List component
  config/build.js
  src/CarrierLogo/index.js
  src/CarrierLogo/index.js.flow
  src/Icon/README.md
  src/Icon/consts.js
  src/List/List.stories.js
  src/List/ListItem/index.js
  src/List/ListItem/index.js.flow
  src/List/README.md
  src/List/__snapshots__/List.stories.storyshot
  src/List/__tests__/__snapshots__/index.test.js.snap
  src/List/__tests__/index.test.js
  src/List/consts.js
  src/List/index.js
  src/List/index.js.flow
  src/index.js
  src/index.js.flow
Labels: New component, process/to-review

#281 WIP: Add new Illustration component
  src/Illustration/Illustration.stories.js
  src/Illustration/README.md
  src/Illustration/__snapshots__/Illustration.stories.storyshot
  src/Illustration/__tests__/__snapshots__/index.test.js.snap
  src/Illustration/__tests__/index.test.js
  src/Illustration/consts.js
  src/Illustration/index.js
  src/Illustration/index.js.flow
  src/index.js
  src/index.js.flow
Labels: process/to-review

#304 FIX: ButtonLink render
  src/ButtonGroup/__snapshots__/ButtonGroup.stories.storyshot
  src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/index.js
  src/InputField/__snapshots__/InputField.stories.storyshot
Labels: process/to-review

#298 NEW: CountryFlag component
  src/CountryFlag/CountryFlag.stories.js
  src/CountryFlag/README.md
  src/CountryFlag/__snapshots__/CountryFlag.stories.storyshot
  src/CountryFlag/__tests__/__snapshots__/index.test.js.snap
  src/CountryFlag/__tests__/index.test.js
  src/CountryFlag/consts.js
  src/CountryFlag/index.js
  src/CountryFlag/index.js.flow
  src/index.js
  src/index.js.flow
Labels: New component, process/to-review

#303 UPDATE: Form components border focuses
  src/Checkbox/__snapshots__/Checkbox.stories.storyshot
  src/Checkbox/index.js
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputField/index.js
  src/Radio/__snapshots__/Radio.stories.storyshot
  src/Radio/index.js
  src/Select/__snapshots__/Select.stories.storyshot
  src/Select/index.js
  src/Textarea/__snapshots__/Textarea.stories.storyshot
  src/Textarea/index.js
Labels: process/to-review

#306 DOCS: Update and add Contribution guideline
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/contribution/README.md
  .github/contribution/commits.md
  .github/contribution/component-design.md
  .github/contribution/icons.md
  .github/contribution/props-convention.md
  .github/contribution/testing-conventions.md
  .github/contribution/theming.md
  .github/orbit-components.png
  .github/orbit-components@2x.png
  readme.md
Labels: documentation, process/to-review

#314 FIX: Root readme.md
  readme.md
Labels: process/to-review

#313 UPDATE: Add new illustrations
  src/Illustration/consts.js
  src/Illustration/index.js.flow
Labels: process/to-review

#326 FIX: Forms disabled state
  src/Checkbox/__snapshots__/Checkbox.stories.storyshot
  src/Checkbox/index.js
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputField/index.js
  src/Radio/__snapshots__/Radio.stories.storyshot
  src/Radio/index.js
  src/Select/__snapshots__/Select.stories.storyshot
  src/Select/index.js
Labels: process/to-review

#309 UPDATE: orbit-design-tokens to 0.1.4
  package.json
  src/Alert/__snapshots__/Alert.stories.storyshot
  src/Alert/__tests__/__snapshots__/index.test.js.snap
  src/Alert/index.js
  src/Badge/__tests__/__snapshots__/index.test.js.snap
  src/Badge/index.js
  src/Button/__snapshots__/Button.stories.storyshot
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/ButtonGroup/__snapshots__/ButtonGroup.stories.storyshot
  src/ButtonGroup/__tests__/__snapshots__/index.test.js.snap
  src/ButtonGroup/index.js
  src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/__snapshots__/Checkbox.stories.storyshot
  src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/index.js
  src/CountryFlag/__tests__/__snapshots__/index.test.js.snap
  src/CountryFlag/index.js
  src/FormFeedback/__tests__/__snapshots__/index.test.js.snap
  src/FormFeedback/index.js
  src/FormLabel/__tests__/__snapshots__/index.test.js.snap
  src/FormLabel/index.js
  src/Heading/__tests__/__snapshots__/index.test.js.snap
  src/Icon/consts.js
  src/Illustration/__tests__/__snapshots__/index.test.js.snap
  src/Illustration/index.js
  src/Illustration/index.js.flow
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputField/__tests__/__snapshots__/index.test.js.snap
  src/InputField/index.js
  src/List/__tests__/__snapshots__/index.test.js.snap
  src/Radio/__snapshots__/Radio.stories.storyshot
  src/Radio/__tests__/__snapshots__/index.test.js.snap
  src/Radio/index.js
  src/Select/__snapshots__/Select.stories.storyshot
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Select/index.js
  src/Separator/__tests__/__snapshots__/index.test.js.snap
  src/Separator/index.js
  src/Text/__tests__/__snapshots__/index.test.js.snap
  src/Text/index.js
  src/TextLink/__snapshots__/TextLink.stories.storyshot
  src/TextLink/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/__snapshots__/Textarea.stories.storyshot
  src/Textarea/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/index.js
  yarn.lock
Labels: process/to-review

#292 NEW: InputGroup component
  src/InputField/README.md
  src/InputField/index.js
  src/InputField/index.js.flow
  src/InputGroup/InputGroup.stories.js
  src/InputGroup/README.md
  src/InputGroup/__snapshots__/InputGroup.stories.storyshot
  src/InputGroup/__tests__/__snapshots__/index.test.js.snap
  src/InputGroup/__tests__/index.test.js
  src/InputGroup/consts.js
  src/InputGroup/index.js
  src/InputGroup/index.js.flow
  src/Select/Select.stories.js
  src/Select/__snapshots__/Select.stories.storyshot
  src/Select/index.js
  src/Select/index.js.flow
  src/index.js
  src/index.js.flow
Labels: New component, process/to-review

#329 DEV: Updated dependencies
  package.json
  yarn.lock
Labels: dependency

#254 NEW: ServiceLogo component
  src/ServiceLogo/README.md
  src/ServiceLogo/ServiceLogo.stories.js
  src/ServiceLogo/__snapshots__/ServiceLogo.stories.storyshot
  src/ServiceLogo/__tests__/__snapshots__/index.test.js.snap
  src/ServiceLogo/__tests__/index.test.js
  src/ServiceLogo/consts.js
  src/ServiceLogo/index.js
  src/ServiceLogo/index.js.flow
  src/index.js
  src/index.js.flow
Labels: New component, process/to-review
