Repository kiwicom/orbit, pull requests merged in 2019-04, with the labels that each got.

#928 UPDATE: Button & ButtonLink accessibility
  src/Button/Button.stories.js
  src/Button/README.md
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/Button/__tests__/index.test.js
  src/Button/index.js
  src/Button/index.js.flow
  src/ButtonLink/ButtonLink.stories.js
  src/ButtonLink/README.md
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/__tests__/index.test.js
  src/ButtonLink/index.js
  src/ButtonLink/index.js.flow
  src/InputStepper/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__tests__/__snapshots__/index.test.js.snap
Labels: Accessibility, Review needed

#969 UPDATE: Icon accessibility options
  config/build.js
  src/Icon/Icon.stories.js
  src/Icon/README.md
  src/Icon/__tests__/__snapshots__/index.test.js.snap
  src/Icon/__tests__/index.test.js
  src/Icon/index.js
  src/Icon/index.js.flow
Labels: Accessibility, Review needed

#945 UPDATE: TripSegment accessibility
  src/TripSegment/README.md
  src/TripSegment/__tests__/__snapshots__/index.test.js.snap
  src/TripSegment/index.js
  src/TripSegment/index.js.flow
  src/common/keyMaps.js
Labels: Accessibility, Review needed

#968 UPDATE: Breadcrumbs onBack button
  src/Breadcrumbs/Breadcrumbs.stories.js
  src/Breadcrumbs/README.md
  src/Breadcrumbs/index.js
  src/Breadcrumbs/index.js.flow
Labels: Enhancement, Review needed

#973 UPDATE: BreadCrumbs rename onGoBack
  src/Breadcrumbs/Breadcrumbs.stories.js
  src/Breadcrumbs/README.md
  src/Breadcrumbs/_tests_/__snapshots__/index.test.js.snap
  src/Breadcrumbs/_tests_/index.test.js
  src/Breadcrumbs/index.js
  src/Breadcrumbs/index.js.flow
Labels: Review needed

#977 FIX: CountryFlag code normalization
  src/CountryFlag/index.js
Labels: Bug, Review needed

#943 UPDATE: DestinationCard accessibility
  src/DestinationCard/DestinationCard.stories.js
  src/DestinationCard/README.md
  src/DestinationCard/_tests_/__snapshots__/index.test.js.snap
  src/DestinationCard/index.js
  src/DestinationCard/index.js.flow
Labels: Accessibility, Review needed

#952 DOCS: Add link to CodeSandbox
  .github/ISSUE_TEMPLATE/bug_report.md
  readme.md
Labels: Documentation

#940 UPDATE: Tooltip accessibility
  src/Tooltip/README.md
  src/Tooltip/Tooltip.stories.js
  src/Tooltip/__tests__/__snapshots__/index.test.js.snap
  src/Tooltip/index.js
  src/Tooltip/index.js.flow
Labels: Accessibility, Review needed

#936 UPDATE: InputStepper accessibility
  src/InputStepper/__tests__/__snapshots__/index.test.js.snap
  src/InputStepper/__tests__/index.test.js
  src/InputStepper/index.js
  src/common/keyMaps.js
Labels: Accessibility, Review needed

#979 FIX: Stack default direction in breakpoints
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/Stack/helpers/getDirection.js
  src/Stack/helpers/getDirection.js.flow
Labels: Bug, Review needed

#988 DOCS: Update mediaQuery
  src/utils/mediaQuery/README.md
Labels: Documentation

#1001 FIX: Modal mount rendering
  src/Modal/ModalFooter/index.js
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Modal/index.js
Labels: Bug, Review needed

#998 FIX: overflowing TripSegment in card
  src/TripSector/index.js
  yarn.lock
Labels: Review needed

#1004 ICONS: Add from orbit 1.0.1
  src/icons/svg/Infant.svg
  src/icons/svg/child.svg
  src/icons/svg/icons.json
Labels: Icons

#989 UPDATE: Add inverted Badges
  src/Badge/Badge.stories.js
  src/Badge/README.md
  src/Badge/consts.js
  src/Badge/index.js
  src/Badge/index.js.flow
Labels: Review needed

#894 NEW: Popover component
  src/Popover/Popover.stories.js
  src/Popover/README.MD
  src/Popover/__tests__/__snapshots__/index.test.js.snap
  src/Popover/__tests__/index.test.js
  src/Popover/components/ContentWrapper.js
  src/Popover/components/ContentWrapper.js.flow
  src/Popover/consts.js
  src/Popover/helpers/calculatePopoverPosition.js
  src/Popover/helpers/calculatePopoverPosition.js.flow
  src/Popover/helpers/resolvePopoverHorizontal.js
  src/Popover/helpers/resolvePopoverHorizontal.js.flow
  src/Popover/helpers/resolvePopoverPosition.js
  src/Popover/helpers/resolvePopoverPosition.js.flow
  src/Popover/hooks/useDimensions.js
  src/Popover/hooks/useDimensions.js.flow
  src/Popover/hooks/useHorizontalPosition.js
  src/Popover/hooks/useHorizontalPosition.js.flow
  src/Popover/hooks/useVerticalPosition.js
  src/Popover/hooks/useVerticalPosition.js.flow
  src/Popover/index.js
  src/Popover/index.js.flow
  src/index.js
  src/index.js.flow
Labels: Review needed

#999 FIX: Illustration fluid behavior
  src/Illustration/index.js
Labels: Review needed

#1021 UPDATE: Remove deprecated Card
  src/_deprecated/Card/Card.stories.js
  src/_deprecated/Card/CardContent/index.js
  src/_deprecated/Card/CardContent/index.js.flow
  src/_deprecated/Card/CardHeader/index.js
  src/_deprecated/Card/CardHeader/index.js.flow
  src/_deprecated/Card/CardSection/index.js
  src/_deprecated/Card/CardSection/index.js.flow
  src/_deprecated/Card/__tests__/index.test.js
  src/_deprecated/Card/index.js
  src/_deprecated/Card/index.js.flow
  src/index.js
  src/index.js.flow
Labels: Review needed

#1011 DEV: Jest tweaks
  jest.json
  package.json
Labels: Review needed

#1016 NEW: Translations layer
  .eslintrc
  .github/dictionary.md
  .github/theming.md
  config/fetchTranslations.js
  package.json
  readme.md
  src/Dictionary/index.js
  src/Dictionary/index.js.flow
  src/Popover/README.MD
  src/Popover/__tests__/__snapshots__/index.test.js.snap
  src/Popover/components/ContentWrapper.js
  src/Popover/index.js.flow
  src/ThemeProvider/README.md
  src/ThemeProvider/index.js
  src/ThemeProvider/index.js.flow
  src/Tooltip/README.md
  src/Tooltip/index.js
  src/Tooltip/index.js.flow
  src/Translate/README.md
  src/Translate/index.js
  src/Translate/index.js.flow
  src/data/dictionary/ar-AE.json
  src/data/dictionary/bg-BG.json
  src/data/dictionary/cs-CZ.json
  src/data/dictionary/da-DK.json
  src/data/dictionary/de-DE.json
  src/data/dictionary/el-GR.json
  src/data/dictionary/en-GB.json
  src/data/dictionary/en-US.json
  src/data/dictionary/es-AR.json
  src/data/dictionary/es-ES.json
  src/data/dictionary/es-MX.json
  src/data/dictionary/fi-FI.json
  src/data/dictionary/fr-FR.json
  src/data/dictionary/he-IL.json
  src/data/dictionary/hu-HU.json
  src/data/dictionary/id-ID.json
  src/data/dictionary/it-IT.json
  src/data/dictionary/ja-JP.json
  src/data/dictionary/ko-KR.json
  src/data/dictionary/lt-LT.json
  src/data/dictionary/nb-NO.json
  src/data/dictionary/nl-NL.json
  src/data/dictionary/pl-PL.json
  src/data/dictionary/pt-PT.json
  src/data/dictionary/ro-RO.json
  src/utils/rtl/RenderInRtl.js
  yarn.lock
Labels: Review needed

#1015 UPDATE: InputGroup accessibility
  src/FormLabel/index.js
  src/FormLabel/index.js.flow
  src/InputGroup/__tests__/__snapshots__/index.test.js.snap
  src/InputGroup/__tests__/index.test.js
  src/InputGroup/index.js
  src/InputGroup/index.js.flow
Labels: Accessibility, Review needed

#996 UPDATE: ChoiceGroup filter usage
  src/ChoiceGroup/ChoiceGroup.stories.js
  src/ChoiceGroup/README.md
  src/ChoiceGroup/__tests__/__snapshots__/index.test.js.snap
  src/ChoiceGroup/__tests__/index.test.js
  src/ChoiceGroup/components/FilterWrapper.js
  src/ChoiceGroup/components/FilterWrapper.js.flow
  src/ChoiceGroup/index.js
  src/ChoiceGroup/index.js.flow
Labels: Changes requested

#1017 NEW: SkipNavigation
  src/Card/CardHeader/index.js
  src/Card/CardHeader/index.js.flow
  src/Card/README.md
  src/Heading/README.md
  src/Heading/index.js
  src/Heading/index.js.flow
  src/SkipNavigation/README.md
  src/SkipNavigation/SkipNavigation.stories.js
  src/SkipNavigation/_tests_/__snapshots__/index.test.js.snap
  src/SkipNavigation/_tests_/index.test.js
  src/SkipNavigation/index.js
  src/SkipNavigation/index.js.flow
  src/index.js
  src/index.js.flow
Labels: Changes requested
