Repository kiwicom/orbit, pull requests merged in 2019-03, with the labels that each got.

#874 FIX: TripSector icon background in IE
  src/TripSector/index.js
Labels: Bug, IE, Review needed

#880 FIX: TripSegment translatation props
  src/TripSegment/README.md
  src/TripSegment/index.js.flow
Labels: Review needed

#886 DOCS: Loader with loading false
  src/Loading/README.md
Labels: Documentation, Review needed

#888 FIX: InputField disabled value in Safari
  src/InputField/index.js
  src/InputStepper/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__tests__/__snapshots__/index.test.js.snap
Labels: Bug

#887 DOCS: Update contribution guides to reflect squash and merge
  .github/contributing.md
  .github/contribution/commits.md
Labels: Documentation, Review needed

#882 ICONS: Add URL of raw SVG to JSON list
  config/build.js
  src/icons/svg/icons.json
Labels: Icons, Review needed

#890 ICONS: Update Seat icon
  src/icons/svg/icons.json
  src/icons/svg/seat.svg
Labels: Icons, Review needed

#883 UPDATE: Add spacing none option to Stack
  src/Stack/README.md
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__tests__/index.test.js
  src/Stack/consts.js
  src/Stack/helpers/getChildrenMargin.js
  src/Stack/index.js.flow
Labels: Enhancement, Review needed

#889 FIX: Badge with translated node
  src/Badge/Badge.stories.js
  src/Badge/__tests__/__snapshots__/index.test.js.snap
  src/Badge/index.js
Labels: Bug, Review needed

#873 ADD: Heading type displaySubtitle
  src/Heading/Heading.stories.js
  src/Heading/README.md
  src/Heading/consts.js
  src/Heading/index.js
  src/Heading/index.js.flow
Labels: Enhancement, Review needed

#878 UPDATE: Adding block prop to Hide component
  src/Hide/Hide.stories.js
  src/Hide/README.md
  src/Hide/_tests_/__snapshots__/index.test.js.snap
  src/Hide/_tests_/index.test.js
  src/Hide/index.js
  src/Hide/index.js.flow
Labels: Changes requested

#634 UPDATE: Add reverseOnRtl to Icon
  config/build.js
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/Hide/_tests_/__snapshots__/index.test.js.snap
  src/Icon/Icon.stories.js
  src/Icon/README.md
  src/Icon/__tests__/__snapshots__/index.test.js.snap
  src/Icon/index.js
  src/Icon/index.js.flow
  src/InputStepper/__tests__/__snapshots__/index.test.js.snap
  src/_deprecated/Card/__snapshots__/Card.stories.storyshot
Labels: RTL, Review needed

#893 UPDATE: Orbit tokens to 0.4.0
  package.json
  src/Alert/__tests__/__snapshots__/index.test.js.snap
  src/Alert/index.js
  src/Badge/__tests__/__snapshots__/index.test.js.snap
  src/Badge/index.js
  src/Breadcrumbs/_tests_/__snapshots__/index.test.js.snap
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/Button/consts.js
  src/Button/index.js
  src/ButtonGroup/__tests__/__snapshots__/index.test.js.snap
  src/ButtonGroup/index.js
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/consts.js
  src/ButtonLink/index.js
  src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  src/ChoiceGroup/__tests__/__snapshots__/index.test.js.snap
  src/CountryFlag/__tests__/__snapshots__/index.test.js.snap
  src/FormFeedback/__tests__/__snapshots__/index.test.js.snap
  src/FormLabel/__tests__/__snapshots__/index.test.js.snap
  src/Heading/__tests__/__snapshots__/index.test.js.snap
  src/Heading/index.js
  src/Hide/_tests_/__snapshots__/index.test.js.snap
  src/Icon/__tests__/__snapshots__/index.test.js.snap
  src/Illustration/__tests__/__snapshots__/index.test.js.snap
  src/InputField/__tests__/__snapshots__/index.test.js.snap
  src/InputFile/__tests__/__snapshots__/index.test.js.snap
  src/InputGroup/__tests__/__snapshots__/index.test.js.snap
  src/InputStepper/__tests__/__snapshots__/index.test.js.snap
  src/List/__tests__/__snapshots__/index.test.js.snap
  src/ListChoice/_tests_/__snapshots__/index.test.js.snap
  src/Loading/__tests__/__snapshots__/index.test.js.snap
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Radio/__tests__/__snapshots__/index.test.js.snap
  src/RatingStars/__tests__/__snapshots__/index.test.js.snap
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Separator/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/Stepper/_tests_/__snapshots__/index.test.js.snap
  src/StopoverArrow/__tests__/__snapshots__/index.test.js.snap
  src/Table/__tests__/__snapshots__/index.test.js.snap
  src/Tag/__tests__/__snapshots__/index.test.js.snap
  src/Text/__tests__/__snapshots__/index.test.js.snap
  src/TextLink/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/__tests__/__snapshots__/index.test.js.snap
  src/Tile/__tests__/__snapshots__/index.test.js.snap
  src/Tooltip/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/TripDate/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/TripLayover/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/__tests__/__snapshots__/index.test.js.snap
  src/TripSegment/__tests__/__snapshots__/index.test.js.snap
  src/utils/Slide/__tests__/__snapshots__/index.test.js.snap
  yarn.lock
Labels: Review needed

#916 UPDATE: Add autocomplete to InputField
  src/InputField/InputField.stories.js
  src/InputField/README.md
  src/InputField/__tests__/__snapshots__/index.test.js.snap
  src/InputField/__tests__/index.test.js
  src/InputField/index.js
  src/InputField/index.js.flow
Labels: Review needed

#911 UPDATE: Add setScrollPosition for Modal
  src/Modal/Modal.stories.js
  src/Modal/README.md
  src/Modal/index.js
Labels: Review needed

#917 DOCS: Add link to component documentation
  src/Alert/index.js.flow
  src/Badge/index.js.flow
  src/Breadcrumbs/index.js.flow
  src/Button/index.js.flow
  src/ButtonGroup/index.js.flow
  src/ButtonLink/index.js.flow
  src/Card/index.js.flow
  src/CarrierLogo/index.js.flow
  src/Checkbox/index.js.flow
  src/ChoiceGroup/index.js.flow
  src/CountryFlag/index.js.flow
  src/Heading/index.js.flow
  src/Hide/index.js.flow
  src/Illustration/index.js.flow
  src/InputField/index.js.flow
  src/InputFile/index.js.flow
  src/InputGroup/index.js.flow
  src/InputStepper/index.js.flow
  src/List/index.js.flow
  src/ListChoice/index.js.flow
  src/Loading/index.js.flow
  src/Modal/index.js.flow
  src/Portal/index.js.flow
  src/Radio/index.js.flow
  src/RatingStars/index.js.flow
  src/Select/index.js.flow
  src/Separator/index.js.flow
  src/ServiceLogo/index.js.flow
  src/Stack/index.js.flow
  src/Stepper/index.js.flow
  src/StopoverArrow/index.js.flow
  src/Table/index.js.flow
  src/Tag/index.js.flow
  src/Text/index.js.flow
  src/TextLink/index.js.flow
  src/Textarea/index.js.flow
  src/Tile/index.js.flow
  src/Tooltip/index.js.flow
  src/TripSector/index.js.flow
  src/TripSegment/index.js.flow
Labels: Review needed

#920 FIX: Modal IE unwanted space between content and footer
  src/Modal/index.js
Labels: IE, Review needed

#895 ADD: DestinationCard
  src/DestinationCard/DestinationCard.stories.js
  src/DestinationCard/README.md
  src/DestinationCard/_tests_/__snapshots__/index.test.js.snap
  src/DestinationCard/_tests_/index.test.js
  src/DestinationCard/consts.js
  src/DestinationCard/index.js
  src/DestinationCard/index.js.flow
  src/LazyImage/index.js
  src/LazyImage/index.js.flow
  src/index.js
  src/index.js.flow
Labels: Review needed

#625 NEW: Sticky component
  src/Sticky/README.md
  src/Sticky/Sticky.stories.js
  src/Sticky/__snapshots__/Sticky.stories.storyshot
  src/Sticky/__tests__/index.test.js
  src/Sticky/index.js
  src/Sticky/index.js.flow
  src/index.js
  src/index.js.flow
  src/utils/scroll/index.js
  src/utils/scroll/index.js.flow
Labels: Review needed

#921 UPDATE: Add duration to TripDate
  src/Badge/index.js
  src/TripSector/README.md
  src/TripSector/TripDate/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/TripDate/index.js
  src/TripSector/TripDate/index.js.flow
  src/TripSector/TripSector.stories.js
Labels: Review needed

#912 FIX: Modal header on mobile in IE
  src/Modal/ModalHeader/index.js
  src/Modal/index.js
Labels: IE, Review needed

#932 UPDATE: ListChoice heading render
  src/ListChoice/_tests_/__snapshots__/index.test.js.snap
  src/ListChoice/index.js
Labels: Accessibility, Review needed

#935 UPDATE: Tag focus
  src/Tag/__tests__/__snapshots__/index.test.js.snap
  src/Tag/index.js
Labels: Accessibility, Review needed

#801 UPDATE: Relaxed country props in CountryFlag
  package.json
  src/CountryFlag/CountryFlag.stories.js
  src/CountryFlag/README.md
  src/CountryFlag/__tests__/index.test.js
  src/CountryFlag/index.js
  src/CountryFlag/index.js.flow
  yarn.lock
Labels: Review needed

#549 NEW: DestinationHeader component
  src/DestinationHeader/DestinationHeader.stories.js
  src/DestinationHeader/README.md
  src/DestinationHeader/_tests_/__snapshots__/index.test.js.snap
  src/DestinationHeader/_tests_/index.test.js
  src/DestinationHeader/consts.js
  src/DestinationHeader/index.js
  src/DestinationHeader/index.js.flow
  src/Heading/index.js
  src/Heading/index.js.flow
  src/index.js
  src/index.js.flow
Labels: Review needed

#926 FIX: TextLink style without href
  src/TextLink/TextLink.stories.js
  src/TextLink/index.js
Labels: Bug

#930 FIX: Illustration fluid behaviour
  src/Illustration/index.js
Labels: Bug

#946 ICONS: Add from orbit 0.33.3
  src/icons/svg/air-conditioning.svg
  src/icons/svg/car-door.svg
  src/icons/svg/fuel.svg
  src/icons/svg/icons.json
  src/icons/svg/transmission.svg
Labels: Icons

#937 UPDATE: Stepper focus
  src/Stepper/index.js
Labels: Accessibility, Review needed

#927 UPDATE: Card accessibility
  src/Card/CardSection/CardSectionHeader/index.js
  src/Card/CardSection/index.js
  src/Card/CardSection/index.js.flow
Labels: Accessibility, Review needed

#951 FIX: InputField placeholder color in Safari
  src/InputField/index.js
  src/InputStepper/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__tests__/__snapshots__/index.test.js.snap
Labels: Bug, Review needed

#949 FIX: Table horizontal scroll in Safari
  src/Table/index.js
Labels: Bug, Review needed

#931 UPDATE: Checkbox accessibility improvement
  src/Checkbox/index.js
Labels: Accessibility, Review needed

#934 UPDATE: RadioButton focus state
  src/Radio/index.js
Labels: Accessibility, Review needed

#956 UPDATE: Add reverse directions to Stack
  src/Stack/README.md
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__tests__/index.test.js
  src/Stack/consts.js
  src/Stack/helpers/getChildrenMargin.js
  src/Stack/helpers/getDirection.js
  src/Stack/helpers/getDirectionSpacingTemplate.js
  src/Stack/helpers/getDirectionSpacingTemplate.js.flow
  src/Stack/index.js.flow
Labels: Enhancement, Review needed

#950 FIX: Stepper and InputStepper onChange callback
  src/InputStepper/index.js
  src/Stepper/_tests_/__snapshots__/index.test.js.snap
  src/Stepper/_tests_/index.test.js
  src/Stepper/index.js
Labels: Bug, Review needed

#958 UPDATE: Modal accessibility
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Modal/consts.js
  src/Modal/index.js
  src/common/keyMaps.js
  src/utils/randomID/index.js
  src/utils/randomID/index.js.flow
Labels: Accessibility, Review needed

#966 UPDATE: Modal accessibility README
  src/Modal/README.md
Labels: Documentation
