Repository kiwicom/orbit, pull requests merged in 2019-05, with the labels that each got.

#1027 FIX: Infant and Child SVG viewBox
  src/icons/svg/Infant.svg
  src/icons/svg/child.svg
  src/icons/svg/icons.json
Labels: Bug, Icons

#1019 UPDATE: Adding Button title prop for accessibility
  package.json
  src/Button/Button.stories.js
  src/Button/README.md
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/Button/__tests__/index.test.js
  src/Button/index.js
  src/Button/index.js.flow
  src/ButtonLink/ButtonLink.stories.js
  src/ButtonLink/README.md
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/__tests__/index.test.js
  src/ButtonLink/index.js
  src/ButtonLink/index.js.flow
  src/CountryFlag/index.js
  yarn.lock
Labels: Accessibility, Review needed

#1037 ICONS: disabling the shrink in flex box
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/Hide/_tests_/__snapshots__/index.test.js.snap
  src/Icon/__tests__/__snapshots__/index.test.js.snap
  src/Icon/index.js
Labels: Review needed

#1039 FIX: Tile expandable dynamic height
  src/Tile/Tile.stories.js
  src/Tile/TileExpandable/index.js
Labels: Review needed

#1043 FIX: import default dictionary file
  src/Translate/index.js
Labels: Review needed

#1038 UPDATE: Add none spaceAfter option
  src/common/getSpacingToken/README.md
  src/common/getSpacingToken/consts.js
  src/common/getSpacingToken/index.js
  src/common/getSpacingToken/index.js.flow
Labels: Review needed

#1044 FIX: Card section collapse on doubleClick
  src/utils/Slide/__tests__/__snapshots__/index.test.js.snap
  src/utils/Slide/__tests__/index.test.js
  src/utils/Slide/index.js
Labels: Review needed

#1041 UPDATE: Mobile fullPage variant for mobile viewport
  src/Modal/Modal.stories.js
  src/Modal/ModalContext.js
  src/Modal/ModalContext.js.flow
  src/Modal/ModalFooter/index.js
  src/Modal/ModalHeader/index.js
  src/Modal/ModalSection/index.js
  src/Modal/README.md
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Modal/index.js
  src/Modal/index.js.flow
Labels: Review needed

#1022 DEV: Update orbit-design-tokens to 0.6.0
  package.json
  src/Alert/__tests__/__snapshots__/index.test.js.snap
  src/Badge/__tests__/__snapshots__/index.test.js.snap
  src/Breadcrumbs/_tests_/__snapshots__/index.test.js.snap
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/ButtonGroup/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  src/ChoiceGroup/__tests__/__snapshots__/index.test.js.snap
  src/CountryFlag/__tests__/__snapshots__/index.test.js.snap
  src/DestinationCard/_tests_/__snapshots__/index.test.js.snap
  src/DestinationHeader/_tests_/__snapshots__/index.test.js.snap
  src/FormFeedback/__tests__/__snapshots__/index.test.js.snap
  src/FormLabel/__tests__/__snapshots__/index.test.js.snap
  src/Heading/__tests__/__snapshots__/index.test.js.snap
  src/Hide/_tests_/__snapshots__/index.test.js.snap
  src/Icon/__tests__/__snapshots__/index.test.js.snap
  src/Illustration/__tests__/__snapshots__/index.test.js.snap
  src/InputField/__tests__/__snapshots__/index.test.js.snap
  src/InputFile/__tests__/__snapshots__/index.test.js.snap
  src/InputGroup/__tests__/__snapshots__/index.test.js.snap
  src/List/__tests__/__snapshots__/index.test.js.snap
  src/ListChoice/_tests_/__snapshots__/index.test.js.snap
  src/Loading/__tests__/__snapshots__/index.test.js.snap
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Popover/__tests__/__snapshots__/index.test.js.snap
  src/Radio/__tests__/__snapshots__/index.test.js.snap
  src/RatingStars/__tests__/__snapshots__/index.test.js.snap
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Separator/__tests__/__snapshots__/index.test.js.snap
  src/SkipNavigation/_tests_/__snapshots__/index.test.js.snap
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/Stepper/_tests_/__snapshots__/index.test.js.snap
  src/StopoverArrow/__tests__/__snapshots__/index.test.js.snap
  src/Table/__tests__/__snapshots__/index.test.js.snap
  src/Tag/__tests__/__snapshots__/index.test.js.snap
  src/Text/__tests__/__snapshots__/index.test.js.snap
  src/TextLink/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/__tests__/__snapshots__/index.test.js.snap
  src/Tile/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/TripDate/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/TripLayover/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/__tests__/__snapshots__/index.test.js.snap
  src/TripSegment/__tests__/__snapshots__/index.test.js.snap
  src/utils/Slide/__tests__/__snapshots__/index.test.js.snap
  yarn.lock
Labels: Review needed

#1047 FIX: overflowing Slide util
  src/Card/CardSection/CardSectionContent/index.js
  src/Tile/TileExpandable/index.js
  src/utils/Slide/index.js
Labels: Review needed

#1042 UPDATE: Draggable tags in InputField
  src/InputField/InputField.stories.js
  src/InputField/InputTags/index.js
  src/InputField/InputTags/index.js.flow
  src/InputField/index.js
Labels: Review needed

#1035 UPDATE: TextLink color in Alert
  src/Alert/consts.js
  src/Alert/index.js
Labels: Review needed

#1050 FIX: Buttons flex for column Stack
  src/Button/index.js
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/index.js
Labels: Bug, Review needed

#1049 UPDATE: Translations
  src/data/dictionary/ar-AE.json
  src/data/dictionary/bg-BG.json
  src/data/dictionary/cs-CZ.json
  src/data/dictionary/da-DK.json
  src/data/dictionary/de-DE.json
  src/data/dictionary/en-GB.json
  src/data/dictionary/es-AR.json
  src/data/dictionary/es-ES.json
  src/data/dictionary/fi-FI.json
  src/data/dictionary/fr-FR.json
  src/data/dictionary/he-IL.json
  src/data/dictionary/hu-HU.json
  src/data/dictionary/it-IT.json
  src/data/dictionary/ja-JP.json
  src/data/dictionary/ko-KR.json
  src/data/dictionary/nb-NO.json
  src/data/dictionary/nl-NL.json
  src/data/dictionary/pl-PL.json
  src/data/dictionary/pt-PT.json
  src/data/dictionary/ro-RO.json
Labels: Review needed

#1036 UPDATE: Stepper exports stateless version
  src/Stepper/README.md
  src/Stepper/Stepper.stories.js
  src/Stepper/StepperStateless/index.js
  src/Stepper/StepperStateless/index.js.flow
  src/Stepper/_tests_/__snapshots__/index.test.js.snap
  src/Stepper/_tests_/index.test.js
  src/Stepper/index.js
  src/Stepper/index.js.flow
  src/index.js
  src/index.js.flow
  src/utils/validateDecrement/__test__/index.test.js
  src/utils/validateDecrement/index.js
  src/utils/validateDecrement/index.js.flow
  src/utils/validateIncrement/__test__/index.test.js
  src/utils/validateIncrement/index.js
  src/utils/validateIncrement/index.js.flow
Labels: Review needed

#1048 DEV: Build umd package for orbit.kiwi
  .eslintignore
  .gitignore
  package.json
  webpack.config.js
  yarn.lock
Labels: Review needed

#983 UPDATE: InputStepper exports stateless version
  src/InputField/index.js.flow
  src/InputStepper/InputStepper.stories.js
  src/InputStepper/InputStepperStateless/index.js
  src/InputStepper/InputStepperStateless/index.js.flow
  src/InputStepper/README.md
  src/InputStepper/__tests__/index.test.js
  src/InputStepper/index.js
  src/InputStepper/index.js.flow
  src/index.js
  src/index.js.flow
Labels: Review needed

#967 UPDATE: Tooltip render
  src/Tooltip/index.js
  src/Tooltip/index.js.flow
Labels: Review needed

#1065 DOCS: Fix mistakes in enums
  src/Loading/README.md
  src/Tooltip/README.md
Labels: Documentation

#1063 FIX: Block buttons in Safari iOS 10
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/Button/index.js
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/index.js
  src/Stack/__tests__/__snapshots__/index.test.js.snap
Labels: Bug, Review needed, Tested

#994 NEW: Layout and Grid component
  src/Hide/helpers/getDisplay.js
  src/Hide/helpers/getDisplay.js.flow
  src/Hide/helpers/getViewportHideStyles.js
  src/Hide/helpers/getViewportHideStyles.js.flow
  src/Hide/index.js
  src/Layout/Layout.stories.js
  src/Layout/LayoutColumn/index.js
  src/Layout/LayoutColumn/index.js.flow
  src/Layout/README.md
  src/Layout/__tests__/__snapshots__/index.test.js.snap
  src/Layout/__tests__/index.test.js
  src/Layout/consts.js
  src/Layout/index.js
  src/Layout/index.js.flow
  src/index.js
  src/index.js.flow
  src/utils/Grid/Grid.stories.js
  src/utils/Grid/README.md
  src/utils/Grid/__tests__/__snapshots__/index.test.js.snap
  src/utils/Grid/__tests__/index.test.js
  src/utils/Grid/helpers/applyGap.js
  src/utils/Grid/helpers/applyGap.js.flow
  src/utils/Grid/helpers/applyGap.test.js
  src/utils/Grid/helpers/autoPlacement.js
  src/utils/Grid/helpers/autoPlacement.js.flow
  src/utils/Grid/helpers/calculateColumnPlacement.js
  src/utils/Grid/helpers/calculateColumnPlacement.js.flow
  src/utils/Grid/helpers/calculateColumnPlacement.test.js
  src/utils/Grid/helpers/calculateRowPlacement.js
  src/utils/Grid/helpers/calculateRowPlacement.js.flow
  src/utils/Grid/helpers/calculateRowPlacement.test.js
  src/utils/Grid/helpers/compatibleGridTemplate.js
  src/utils/Grid/helpers/compatibleGridTemplate.js.flow
  src/utils/Grid/helpers/getDisplay.js
  src/utils/Grid/helpers/getDisplay.js.flow
  src/utils/Grid/helpers/getProperty.js
  src/utils/Grid/helpers/getProperty.js.flow
  src/utils/Grid/helpers/getViewportGridStyles.js
  src/utils/Grid/helpers/getViewportGridStyles.js.flow
  src/utils/Grid/helpers/getViewportIEGridStyles.js
  src/utils/Grid/helpers/getViewportIEGridStyles.js.flow
  src/utils/Grid/helpers/insertGap.js
  src/utils/Grid/helpers/insertGap.js.flow
  src/utils/Grid/helpers/insertGap.test.js
  src/utils/Grid/helpers/lengthOf.js
  src/utils/Grid/helpers/lengthOf.js.flow
  src/utils/Grid/helpers/lengthOf.test.js
  src/utils/Grid/helpers/realCellsCount.js
  src/utils/Grid/helpers/realCellsCount.js.flow
  src/utils/Grid/helpers/realCellsCount.test.js
  src/utils/Grid/helpers/splitToWords.js
  src/utils/Grid/helpers/splitToWords.js.flow
  src/utils/Grid/helpers/splitToWords.test.js
  src/utils/Grid/index.js
  src/utils/Grid/index.js.flow
Labels: Review needed, Tested

#1000 UPDATE: Buttons active state
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/Button/consts.js
  src/Button/helpers/getButtonBoxShadow.js
  src/Button/helpers/getButtonBoxShadow.js.flow
  src/Button/helpers/getButtonSpacing.js
  src/Button/helpers/getButtonSpacing.js.flow
  src/Button/helpers/getIconSpacing.js
  src/Button/helpers/getIconSpacing.js.flow
  src/Button/helpers/getSizeToken.js
  src/Button/helpers/getSizeToken.js.flow
  src/Button/helpers/getTypeToken.js
  src/Button/helpers/getTypeToken.js.flow
  src/Button/index.js
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/consts.js
  src/ButtonLink/helpers/getButtonLinkBoxShadow.js
  src/ButtonLink/helpers/getButtonLinkBoxShadow.js.flow
  src/ButtonLink/helpers/getButtonLinkSpacing.js
  src/ButtonLink/helpers/getButtonLinkSpacing.js.flow
  src/ButtonLink/helpers/getIconSpacing.js
  src/ButtonLink/helpers/getIconSpacing.js.flow
  src/ButtonLink/helpers/getSizeToken.js
  src/ButtonLink/helpers/getSizeToken.js.flow
  src/ButtonLink/helpers/getTypeToken.js
  src/ButtonLink/helpers/getTypeToken.js.flow
  src/ButtonLink/index.js
  src/ButtonLink/index.js.flow
  src/Stack/__tests__/__snapshots__/index.test.js.snap
Labels: Review needed
