Repository kiwicom/orbit, pull requests merged in 2019-07, with the labels that each got.

#1122 FIX: TextLink default component render
  src/TextLink/index.js
Labels: Bug, Review needed

#1132 DOCS: wrong component name of Illustration
  src/Illustration/README.md
Labels: Bug, Documentation

#1133 FIX: ListItem flex in IE
  src/List/ListItem/index.js
Labels: Bug, IE

#1135 ICONS: New for seating
  src/icons/svg/QR-code.svg
  src/icons/svg/seat-aisle.svg
  src/icons/svg/seat-extra-legroom.svg
  src/icons/svg/seat-window.svg
  src/icons/svg/user-group.svg
Labels: Icons, Review needed

#1137 FIX: Disabled link Buttons shouldn't be clickable
  src/Button/index.js
  src/ButtonLink/index.js
Labels: Bug, Review needed

#1142 FIX: Anchor in Alert font weight
  src/TextLink/index.js
Labels: Bug, Review needed

#1138 FIX: Tooltip preferredPosition on RTL
  src/Tooltip/Tooltip.stories.js
  src/Tooltip/consts.js
  src/Tooltip/index.js
Labels: Bug, RTL, Review needed

#1141 NEW: CallOutBanner component
  src/CallOutBanner/CallOutBanner.stories.js
  src/CallOutBanner/README.md
  src/CallOutBanner/_tests_/__snapshots__/index.test.js.snap
  src/CallOutBanner/_tests_/index.test.js
  src/CallOutBanner/index.js
  src/CallOutBanner/index.js.flow
  src/index.js
  src/index.js.flow
Labels: Enhancement, Review needed

#1054 NEW: Slider component
  src/Loading/Loading.stories.js
  src/Loading/__tests__/index.test.js
  src/Loading/consts.js
  src/Loading/index.js
  src/Slider/README.md
  src/Slider/Slider.stories.js
  src/Slider/_tests_/__snapshots__/index.test.js.snap
  src/Slider/_tests_/index.test.js
  src/Slider/components/Bar/_tests_/__snapshots__/index.test.js.snap
  src/Slider/components/Bar/_tests_/index.test.js
  src/Slider/components/Bar/index.js
  src/Slider/components/Bar/index.js.flow
  src/Slider/components/Handle/_tests_/__snapshots__/index.test.js.snap
  src/Slider/components/Handle/_tests_/index.test.js
  src/Slider/components/Handle/index.js
  src/Slider/components/Handle/index.js.flow
  src/Slider/components/Histogram/_tests_/__snapshots__/index.test.js.snap
  src/Slider/components/Histogram/_tests_/index.test.js
  src/Slider/components/Histogram/index.js
  src/Slider/components/Histogram/index.js.flow
  src/Slider/consts.js
  src/Slider/index.js
  src/Slider/index.js.flow
  src/Slider/utils/_tests_/index.test.js
  src/Slider/utils/calculateCountOf.js
  src/Slider/utils/calculateCountOf.js.flow
  src/common/keyMaps.js
  src/index.js
  src/index.js.flow
Labels: Enhancement, Review needed, Tested

#1139 FIX: Badge with translated multiline node
  src/Badge/__tests__/__snapshots__/index.test.js.snap
  src/Badge/index.js
Labels: Bug, Review needed

#1150 DOCS: Fix Slider valueDescription
  src/Slider/README.md
Labels: Documentation, Review needed

#1149 DOCS: Fix Pagination onPageChange type
  src/Pagination/README.md
Labels: Documentation, Review needed

#1147 DOCS: Fix Icon ariaHidden and ariaLabel property description
  src/Icon/README.md
Labels: Documentation, Review needed

#1146 DOCS: Fix Hide on property type
  src/Hide/README.md
Labels: Documentation, Review needed

#1144 FIX: InputGroup child ref
  src/InputGroup/__tests__/index.test.js
  src/InputGroup/index.js
Labels: Bug, Review needed

#1152 UPDATE: Add missing Badge inverted variants
  src/Badge/Badge.stories.js
  src/Badge/README.md
  src/Badge/consts.js
  src/Badge/index.js
  src/Badge/index.js.flow
Labels: Enhancement, Review needed

#1148 DOCS: Fix InputFile allowedFileTypes property description and type
  src/InputFile/README.md
Labels: Documentation, Review needed

#1140 NEW: Collapse component
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/helpers/getButtonLinkBoxShadow.js
  src/ChoiceGroup/components/FilterWrapper.js
  src/Collapse/Collapse.stories.js
  src/Collapse/README.md
  src/Collapse/_tests_/index.test.js
  src/Collapse/index.js
  src/Collapse/index.js.flow
  src/Slider/components/Handle/index.js
  src/utils/Slide/__tests__/__snapshots__/index.test.js.snap
  src/utils/Slide/index.js
  src/utils/Slide/index.js.flow
Labels: Enhancement, Review needed

#1129 UPDATE: Better compression for Illustrations
  src/Illustration/Illustration.stories.js
  src/Illustration/IllustrationList.js
  src/Illustration/__tests__/index.test.js
  src/Illustration/index.js
Labels: Review needed

#1155 DOCS: Fix default name in CountryFlag
  src/CountryFlag/README.md
Labels: Documentation, Review needed
