Repository kiwicom/orbit, pull requests merged in 2019-06, with the labels that each got.

#1075 UPDATE: SkipNavigation smaller inputs
  src/SkipNavigation/_tests_/__snapshots__/index.test.js.snap
  src/SkipNavigation/index.js
Labels: Review needed

#1072 UPDATE: Accessibility of ChoiceGroup
  src/ChoiceGroup/__tests__/__snapshots__/index.test.js.snap
  src/ChoiceGroup/__tests__/index.test.js
  src/ChoiceGroup/index.js
  src/Heading/Heading.stories.js
  src/Heading/README.md
  src/Heading/index.js
  src/Heading/index.js.flow
Labels: Accessibility, Review needed

#1074 UPDATE: TextLink Accessibility
  src/TextLink/TextLink.stories.js
  src/TextLink/__tests__/index.test.js
  src/TextLink/index.js
Labels: Review needed

#1073 DEV: Update flow to 0.99.1
  flow-typed/npm/styled-components_v3.x.x.js
  flow-typed/npm/styled-components_v4.x.x.js
  package.json
  src/ChoiceGroup/__tests__/__snapshots__/index.test.js.snap
  src/ChoiceGroup/index.js
  src/Modal/ModalFooter/index.js
  src/Modal/ModalHeader/index.js
  src/Modal/ModalSection/index.js
  src/fromPlainObject.js.flow
  src/getTokens.js.flow
  src/index.js.flow
  src/utils/mediaQuery/index.js.flow
  yarn.lock
Labels: Review needed

#1059 NEW: SkipLink
  src/Heading/Heading.stories.js
  src/Heading/__tests__/__snapshots__/index.test.js.snap
  src/Heading/__tests__/index.test.js
  src/Heading/index.js
  src/SkipLink/README.md
  src/SkipLink/SkipLink.stories.js
  src/SkipLink/_test_/__snapshots__/index.test.js.snap
  src/SkipLink/_test_/index.test.js
  src/SkipLink/index.js
  src/SkipLink/index.js.flow
  src/Text/README.md
  src/Text/Text.stories.js
  src/Text/__tests__/__snapshots__/index.test.js.snap
  src/Text/__tests__/index.test.js
  src/Text/index.js
  src/Text/index.js.flow
Labels: Accessibility, Review needed

#1086 UPDATE: Updating accessibility in InputField
  config/enzymeConfig.js
  src/ChoiceGroup/__tests__/index.test.js
  src/InputField/InputField.stories.js
  src/InputField/README.md
  src/InputField/__tests__/__snapshots__/index.test.js.snap
  src/InputField/__tests__/index.test.js
  src/InputField/index.js
  src/InputField/index.js.flow
  src/Stack/__tests__/__snapshots__/index.test.js.snap
Labels: Review needed

#1095 FIX: Tooltip arrow position
  src/Tooltip/helpers/resolveTooltipArrowAlign.js
Labels: Bug

#1103 FIX: Tooltip close button
  src/Tooltip/index.js
Labels: Review needed

#1090 UPDATE: Alert inlineActions prop
  src/Alert/Alert.stories.js
  src/Alert/README.md
  src/Alert/__tests__/__snapshots__/index.test.js.snap
  src/Alert/index.js
  src/Alert/index.js.flow
Labels: Review needed

#1107 FIX: LayoutColumn element type and docs
  src/Layout/LayoutColumn/index.js.flow
  src/Layout/README.md
Labels: Documentation

#1105 UPDATE: Deprecate connected prop in ButtonGroup
  src/ButtonGroup/ButtonGroup.stories.js
  src/ButtonGroup/index.js
Labels: Review needed

#703 NEW: Pagination component
  src/Button/index.js.flow
  src/ButtonLink/index.js.flow
  src/Pagination/Pagination.stories.js
  src/Pagination/README.md
  src/Pagination/__tests__/__snapshots__/index.test.js.snap
  src/Pagination/__tests__/index.test.js
  src/Pagination/components/ActiveButton.js
  src/Pagination/components/ActiveButton.js.flow
  src/Pagination/components/CompactPages.js
  src/Pagination/components/CompactPages.js.flow
  src/Pagination/components/PageButtonLink.js
  src/Pagination/components/PageButtonLink.js.flow
  src/Pagination/components/Pages.js
  src/Pagination/components/Pages.js.flow
  src/Pagination/consts.js
  src/Pagination/index.js
  src/Pagination/index.js.flow
  src/Stack/README.md
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/Stack/index.js
  src/Stack/index.js.flow
  src/index.js
  src/index.js.flow
Labels: Review needed

#1062 UPDATE: Added missing translations in components
  src/Alert/__tests__/index.test.js
  src/Alert/index.js
  src/Breadcrumbs/_tests_/__snapshots__/index.test.js.snap
  src/Breadcrumbs/_tests_/index.test.js
  src/Breadcrumbs/index.js
  src/Card/__tests__/index.test.js
  src/Card/index.js
  src/DestinationHeader/_tests_/__snapshots__/index.test.js.snap
  src/DestinationHeader/_tests_/index.test.js
  src/DestinationHeader/index.js
  src/Dictionary/index.js
  src/Dictionary/index.js.flow
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Modal/__tests__/index.test.js
  src/Modal/index.js
  src/Modal/index.js.flow
  src/Translate/__tests__/index.test.js
  src/Translate/index.js
  src/Translate/index.js.flow
Labels: Review needed

#1110 FIX: children refs inside ModalFooter
  src/Modal/ModalFooter/index.js
Labels: Review needed

#1109 UPDATE: Add component property to TextLink
  src/Breadcrumbs/BreadcrumbsItem/index.js
  src/Breadcrumbs/BreadcrumbsItem/index.js.flow
  src/Breadcrumbs/_tests_/__snapshots__/index.test.js.snap
  src/Button/index.js.flow
  src/ButtonLink/index.js.flow
  src/TextLink/README.md
  src/TextLink/__tests__/__snapshots__/index.test.js.snap
  src/TextLink/index.js
  src/TextLink/index.js.flow
  src/common/common.js.flow
Labels: Review needed

#1114 FIX: Invisible tags inside InputField on iOS
  src/InputField/InputTags/index.js
Labels: Bug, Review needed

#1112 UPDATE: Tooltip enabled prop
  src/Tooltip/README.md
  src/Tooltip/Tooltip.stories.js
  src/Tooltip/index.js
  src/Tooltip/index.js.flow
Labels: Review needed

#1115 UPDATE: Modal click outside condition
  src/Modal/index.js
Labels: Enhancement, Review needed
