Repository kiwicom/orbit, pull requests merged in 2019-11, with the labels that each got.

#1358 UPDATE: PricingTable layout for less than 3 child
  src/PricingTable/PricingTable.stories.js
  src/PricingTable/PricingTableItem/index.js
  src/PricingTable/index.js
Labels: Review needed

#1357 FIX: PricingTable double render on desktop
  src/PricingTable/index.js
Labels: Review needed

#1362 FIX: Buttons line-height for multiline content
  src/Button/index.js
  src/ButtonLink/index.js
Labels: Bug, Review needed

#1356 UPDATE: Popover getScrollableParent execution optimization
  src/Popover/components/ContentWrapper.js
  src/Popover/hooks/useDimensions.js
  src/Popover/hooks/useDimensions.js.flow
Labels: Review needed

#1360 UPDATE: Popover fixed actions
  src/Popover/Popover.stories.js
  src/Popover/__tests__/index.test.js
  src/Popover/components/ContentWrapper.js
  src/Popover/index.js
Labels: Review needed

#1366 FIX: Tooltip children wrapper set to inline-flex
  src/Radio/Radio.stories.js
  src/Tooltip/index.js
Labels: Review needed

#1371 FIX: Illustration's display size
  src/Illustration/consts.js
  src/Illustration/index.js
Labels: Bug

#1370 FIX: ChoiceGroup filter hover and focus
  src/ChoiceGroup/components/FilterWrapper.js
Labels: IE, Review needed

#1374 FIX: Select autofill text color
  src/Select/index.js
Labels: Review needed

#1373 FIX: Forwarding of refs
  src/Button/index.js
  src/Button/index.js.flow
  src/ButtonLink/index.js
  src/ButtonLink/index.js.flow
  src/Checkbox/index.js
  src/InputField/index.js
  src/InputFile/index.js
  src/InputStepper/index.js
  src/Radio/index.js
  src/Select/index.js
  src/Slider/components/Bar/index.js
  src/Textarea/index.js
Labels: Bug, Review needed

#1388 FIX: Pricing table datatest
  src/PricingTable/PricingTable.stories.js
  src/PricingTable/PricingTableItem/index.js
  src/PricingTable/index.js
Labels: Review needed

#1380 UPDATE: StopoverArrow icon shapes
  src/StopoverArrow/__tests__/index.test.js
  src/StopoverArrow/index.js
Labels: Review needed

#1379 UPDATE: Icons build script - smaller size of bundle
  config/build.js
Labels: Icons, Review needed

#1378 ICONS: Syncing with orbit sketch 2.0.0
  src/icons/svg/anywhere.svg
  src/icons/svg/arrow-down.svg
  src/icons/svg/arrow-up.svg
  src/icons/svg/logout.svg
  src/icons/svg/new-window.svg
  src/icons/svg/notification-add.svg
  src/icons/svg/notification-on.svg
  src/icons/svg/show-less.svg
  src/icons/svg/show-more.svg
  src/icons/svg/terminal.svg
  src/icons/svg/trip.svg
Labels: Icons, Review needed

#1377 FIX: Missing aria-labels in our codebase
  src/Collapse/index.js
  src/InputStepper/InputStepper.stories.js
  src/InputStepper/README.md
  src/InputStepper/__tests__/index.test.js
  src/InputStepper/index.js
  src/Stepper/_tests_/index.test.js
  src/data/dictionary/en-GB.json
  src/data/dictionary/ms-MY.json
Labels: Review needed
