Repository kiwicom/orbit, pull requests merged in 2019-08, with the labels that each got.

#1161 FIX: Popover controlled handlers
  src/Popover/index.js
Labels: Bug, Review needed

#1162 FIX: UMD package without React
  webpack.config.js
Labels: Review needed

#1163 DEV: Uploading icons font to npm
  package.json
  src/Icon/README.md
Labels: Review needed

#1164 DEV: Update yarn.lock
  yarn.lock
Labels: Review needed

#1159 FIX: Tooltip content scrolling
  src/Tooltip/Tooltip.stories.js
  src/Tooltip/index.js
Labels: Bug, Review needed

#1145 FIX: Slider onTouchMove event and calculation when zoomed
  src/Slider/index.js
  src/utils/boundingClientRect/index.js
  src/utils/boundingClientRect/index.js.flow
Labels: Bug, Review needed

#1160 NEW: Truncate component
  src/TripSegment/__tests__/__snapshots__/index.test.js.snap
  src/TripSegment/index.js
  src/Truncate/README.md
  src/Truncate/Truncate.stories.js
  src/Truncate/__tests__/index.test.js
  src/Truncate/index.js
  src/Truncate/index.js.flow
  src/index.js
  src/index.js.flow
Labels: Enhancement, Review needed

#1158 FIX: Popover position when scrolled
  src/Popover/README.MD
  src/Popover/__tests__/__snapshots__/index.test.js.snap
  src/Popover/components/ContentWrapper.js
  src/Popover/helpers/calculateHorizontalPosition.js
  src/Popover/helpers/calculateHorizontalPosition.js.flow
  src/Popover/helpers/calculateVerticalPosition.js
  src/Popover/helpers/calculateVerticalPosition.js.flow
  src/Popover/hooks/useDimensions.js
  src/Popover/hooks/useHorizontalPosition.js
  src/Popover/hooks/useHorizontalPosition.js.flow
  src/Popover/hooks/useVerticalPosition.js
  src/Popover/hooks/useVerticalPosition.js.flow
  src/Popover/index.js
  src/Popover/index.js.flow
Labels: Bug, Review needed, To test

#1167 UPDATE: Popover overlapped option
  src/Popover/Popover.stories.js
  src/Popover/README.MD
  src/Popover/__tests__/__snapshots__/index.test.js.snap
  src/Popover/__tests__/index.test.js
  src/Popover/components/ContentWrapper.js
  src/Popover/components/ContentWrapper.js.flow
  src/Popover/helpers/resolvePopoverPosition.js
  src/Popover/index.js
  src/Popover/index.js.flow
Labels: Review needed

#1170 UPDATE: Compression in Illustration list
  config/build.js
Labels: Review needed

#1171 FIX: Modal setScrollPosition falsey condition
  src/Modal/index.js
Labels: Review needed

#1172 UPDATE: dataTest for Table sub-components
  src/Table/README.md
  src/Table/TableBody/index.js
  src/Table/TableBody/index.js.flow
  src/Table/TableCell/index.js
  src/Table/TableCell/index.js.flow
  src/Table/TableHead/index.js
  src/Table/TableHead/index.js.flow
  src/Table/TableRow/index.js
  src/Table/TableRow/index.js.flow
  src/Table/__tests__/index.test.js
Labels: Review needed

#1169 UPDATE: Add warning to attention types or colors
  src/ButtonGroup/index.js
  src/Icon/index.js
  src/RatingStars/index.js
  src/Text/Text.stories.js
  src/Text/index.js
  src/TripSector/TripDate/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/TripDate/index.js
  src/TripSegment/__tests__/__snapshots__/index.test.js.snap
  src/TripSegment/index.js
Labels: Review needed

#1178 UPDATE: Add BUDFastTrack illustration
  src/Illustration/consts.js
Labels: Review needed

#1179 DEV: Update orbit-design-tokens to 0.6.6
  package.json
  src/Alert/__tests__/__snapshots__/index.test.js.snap
  src/Badge/__tests__/__snapshots__/index.test.js.snap
  src/Breadcrumbs/_tests_/__snapshots__/index.test.js.snap
  src/Button/__tests__/__snapshots__/index.test.js.snap
  src/ButtonGroup/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/CallOutBanner/_tests_/__snapshots__/index.test.js.snap
  src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  src/ChoiceGroup/__tests__/__snapshots__/index.test.js.snap
  src/CountryFlag/__tests__/__snapshots__/index.test.js.snap
  src/DestinationCard/_tests_/__snapshots__/index.test.js.snap
  src/DestinationHeader/_tests_/__snapshots__/index.test.js.snap
  src/FormFeedback/__tests__/__snapshots__/index.test.js.snap
  src/FormLabel/__tests__/__snapshots__/index.test.js.snap
  src/Heading/__tests__/__snapshots__/index.test.js.snap
  src/Hide/_tests_/__snapshots__/index.test.js.snap
  src/Icon/__tests__/__snapshots__/index.test.js.snap
  src/Illustration/__tests__/__snapshots__/index.test.js.snap
  src/InputField/__tests__/__snapshots__/index.test.js.snap
  src/InputFile/__tests__/__snapshots__/index.test.js.snap
  src/InputGroup/__tests__/__snapshots__/index.test.js.snap
  src/Layout/__tests__/__snapshots__/index.test.js.snap
  src/List/__tests__/__snapshots__/index.test.js.snap
  src/ListChoice/_tests_/__snapshots__/index.test.js.snap
  src/Loading/__tests__/__snapshots__/index.test.js.snap
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Popover/__tests__/__snapshots__/index.test.js.snap
  src/Radio/__tests__/__snapshots__/index.test.js.snap
  src/RatingStars/__tests__/__snapshots__/index.test.js.snap
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Separator/__tests__/__snapshots__/index.test.js.snap
  src/SkipLink/_test_/__snapshots__/index.test.js.snap
  src/SkipNavigation/_tests_/__snapshots__/index.test.js.snap
  src/Slider/_tests_/__snapshots__/index.test.js.snap
  src/Slider/components/Bar/_tests_/__snapshots__/index.test.js.snap
  src/Slider/components/Handle/_tests_/__snapshots__/index.test.js.snap
  src/Slider/components/Histogram/_tests_/__snapshots__/index.test.js.snap
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/StopoverArrow/__tests__/__snapshots__/index.test.js.snap
  src/Table/__tests__/__snapshots__/index.test.js.snap
  src/Tag/__tests__/__snapshots__/index.test.js.snap
  src/Text/__tests__/__snapshots__/index.test.js.snap
  src/TextLink/__tests__/__snapshots__/index.test.js.snap
  src/Textarea/__tests__/__snapshots__/index.test.js.snap
  src/Tile/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/TripDate/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/TripLayover/__tests__/__snapshots__/index.test.js.snap
  src/TripSector/__tests__/__snapshots__/index.test.js.snap
  src/TripSegment/__tests__/__snapshots__/index.test.js.snap
  src/utils/Grid/__tests__/__snapshots__/index.test.js.snap
  src/utils/Slide/__tests__/__snapshots__/index.test.js.snap
  yarn.lock
Labels: Review needed

#1183 Fix: Missing key in pagination
  src/Pagination/components/Pages.js
Labels: Review needed

#1184 UPDATE: Add Error404 illustration
  src/Illustration/README.md
  src/Illustration/consts.js
Labels: Review needed

#1181 UPDATE: Refactor Tooltip to hooks
  src/Tooltip/__tests__/__snapshots__/index.test.js.snap
  src/Tooltip/components/TooltipContent.js
  src/Tooltip/components/TooltipContent.js.flow
  src/Tooltip/helpers/__tests__/calculateTooltipAlign.test.js
  src/Tooltip/helpers/__tests__/calculateTooltipPosition.test.js
  src/Tooltip/helpers/__tests__/resolveContainerAlign.test.js
  src/Tooltip/helpers/__tests__/resolveContainerPosition.test.js
  src/Tooltip/helpers/__tests__/resolveTooltipArrowAlign.test.js
  src/Tooltip/helpers/__tests__/resolveTooltipArrowPosition.test.js
  src/Tooltip/helpers/__tests__/sortPositionsAndAligns.test.js
  src/Tooltip/helpers/__tests__/tooltipArrowStyle.test.js
  src/Tooltip/helpers/__tests__/tooltipPadding.test.js
  src/Tooltip/helpers/__tests__/tooltipSize.test.js
  src/Tooltip/helpers/calculateTooltipAlign.js
  src/Tooltip/helpers/calculateTooltipAlign.js.flow
  src/Tooltip/helpers/calculateTooltipPosition.js
  src/Tooltip/helpers/calculateTooltipPosition.js.flow
  src/Tooltip/helpers/sortPositionsAndAligns.js
  src/Tooltip/helpers/sortPositionsAndAligns.js.flow
  src/Tooltip/helpers/switchPreferredPosition.js
  src/Tooltip/helpers/switchPreferredPosition.js.flow
  src/Tooltip/hooks/__tests__/useDimensions.test.js
  src/Tooltip/hooks/useDimensions.js
  src/Tooltip/hooks/useDimensions.js.flow
  src/Tooltip/index.js
  src/Tooltip/index.js.flow
  src/hooks/useTheme.js
  src/hooks/useTheme.js.flow
Labels: Review needed

#1091 DEV: Unifying randomID implemenations
  src/ChoiceGroup/__tests__/__snapshots__/index.test.js.snap
  src/ChoiceGroup/index.js
  src/DestinationCard/_tests_/__snapshots__/index.test.js.snap
  src/DestinationCard/index.js
  src/InputField/index.js
  src/InputGroup/__tests__/__snapshots__/index.test.js.snap
  src/InputGroup/__tests__/index.test.js
  src/InputGroup/index.js
  src/InputGroup/index.js.flow
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Modal/index.js
  src/Stack/__tests__/__snapshots__/index.test.js.snap
Labels: Review needed

#1185 FIX: IE boundingRect positions
  src/utils/boundingClientRect/index.js
Labels: IE, Review needed

#1191 UPDATE: Add IATA service logo
  src/ServiceLogo/consts.js
Labels: Review needed

#1188 FIX: Tooltip calculation when scrolled
  src/Tooltip/consts.js
  src/Tooltip/helpers/__tests__/calculateTooltipAlign.test.js
  src/Tooltip/helpers/__tests__/calculateTooltipPosition.test.js
  src/Tooltip/helpers/__tests__/resolveContainerAlign.test.js
  src/Tooltip/helpers/__tests__/resolveContainerPosition.test.js
  src/Tooltip/helpers/__tests__/resolveTooltipArrowAlign.test.js
  src/Tooltip/helpers/__tests__/tooltipPadding.test.js
  src/Tooltip/helpers/calculateTooltipAlign.js
  src/Tooltip/helpers/calculateTooltipPosition.js
  src/Tooltip/hooks/useDimensions.js
  src/Tooltip/index.js.flow
Labels: Review needed

#1190 UPDATE: CountryFlag maybe type for code property
  src/CountryFlag/index.js
  src/CountryFlag/index.js.flow
Labels: Review needed

#1192 DOCS: Fix missing dataTest for Tile
  src/Tile/README.md
Labels: Documentation, Review needed
