Repository kiwicom/orbit, pull requests merged in 2019-09, with the labels that each got.

#1195 UPDATE: Add Axa service logo
  src/ServiceLogo/consts.js
Labels: Review needed

#1194 FIX: CountryFlag shrink
  src/CountryFlag/index.js
Labels: Review needed

#1196 FIX: Tile arrow padding
  src/Tile/TileHeader/index.js
Labels: Review needed

#1201 UPDATE: New service logos
  src/ServiceLogo/consts.js
Labels: Review needed

#1200 UPDATE: Tile composability
  src/CountryFlag/index.js
  src/Tile/Tile.stories.js
  src/Tile/TileHeader/index.js
  src/Tile/TileHeader/index.js.flow
Labels: Review needed

#1202 UPDATE: Textarea rows attribute and min-height lock
  src/Textarea/README.md
  src/Textarea/Textarea.stories.js
  src/Textarea/index.js
  src/Textarea/index.js.flow
Labels: Review needed

#1203 DOCS: Add missing service logos
  src/ServiceLogo/README.md
Labels: Documentation, Review needed

#995 UPDATE: Use Slide in TripSegment
  src/TripSegment/__tests__/__snapshots__/index.test.js.snap
  src/TripSegment/index.js
  src/TripSegment/index.js.flow
  src/utils/Slide/index.js
Labels: Review needed

#1237 UPDATE: Select not-allowed cursor for disabled state
  src/Select/index.js
Labels: Review needed

#1235 FIX: ListChoice accessibility role
  src/ListChoice/_tests_/__snapshots__/index.test.js.snap
  src/ListChoice/index.js
Labels: Review needed

#1226 FIX: Text in Tooltip underline on multiple rows
  src/Tooltip/Tooltip.stories.js
  src/Tooltip/index.js
Labels: Review needed

#1231 FIX: Multiple Popovers close and open
  src/Popover/Popover.stories.js
  src/Popover/__tests__/__snapshots__/index.test.js.snap
  src/Popover/components/ContentWrapper.js
  src/hooks/useClickOutside.js
  src/hooks/useClickOutside.js.flow
Labels: Review needed

#1242 FIX: FormFeedback flow file
  src/ChoiceGroup/index.js
  src/FormFeedback/index.js.flow
Labels: Review needed

#1236 FIX: Checkbox event bubbling when readOnly
  src/Checkbox/Checkbox.stories.js
  src/Checkbox/__tests__/__snapshots__/index.test.js.snap
  src/Checkbox/index.js
Labels: Review needed

#1241 UPDATE: Default element of Heading component
  src/Heading/README.md
  src/Heading/index.js
Labels: Review needed

#1246 UPDATE: extending Stack to have stretch
  src/Stack/README.md
  src/Stack/consts.js
  src/Stack/helpers/getAlign.js
  src/Stack/index.js.flow
Labels: Review needed

#1247 UPDATE: Stopping Tooltip event propagation
  src/Tooltip/index.js
Labels: Review needed

#1254 FIX: ListItem span width
  src/List/ListItem/index.js
Labels: Review needed

#1252 FIX: Popover toggle close
  src/Popover/components/ContentWrapper.js.flow
  src/Popover/index.js
  src/hooks/useClickOutside.js.flow
Labels: Review needed

#1253 UPDATE: InputField inputMode property
  src/InputField/InputField.stories.js
  src/InputField/README.md
  src/InputField/__tests__/__snapshots__/index.test.js.snap
  src/InputField/__tests__/index.test.js
  src/InputField/consts.js
  src/InputField/index.js
  src/InputField/index.js.flow
Labels: Review needed

#1229 NEW: PricingTable component
  src/List/List.stories.js
  src/List/ListItem/index.js
  src/List/ListItem/index.js.flow
  src/List/README.md
  src/List/consts.js
  src/List/index.js
  src/List/index.js.flow
  src/PricingTable/PricingTable.stories.js
  src/PricingTable/PricingTableItem/index.js
  src/PricingTable/PricingTableItem/index.js.flow
  src/PricingTable/README.md
  src/PricingTable/__tests__/__snapshots__/index.test.js.snap
  src/PricingTable/__tests__/index.test.js
  src/PricingTable/index.js
  src/PricingTable/index.js.flow
  src/hooks/useMediaQuery.js
  src/hooks/useMediaQuery.js.flow
  src/index.js
  src/index.js.flow
Labels: Review needed

#1173 ICONS: Update icon font generator with replacements
  config/build.js
  config/createSVGFont.js
  src/icons/svg/google.svg
  src/icons/svg/mobile/google.svg
Labels: Review needed

#1277 FIX: TripSegment in IE
  src/TripSegment/index.js
Labels: IE, Review needed, Tested

#1278 FIX: Buttons max-width in IE
  src/Button/index.js
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/index.js
  src/Stack/__tests__/__snapshots__/index.test.js.snap
Labels: Review needed, Tested
