Repository kiwicom/orbit, pull requests merged in 2019-10, with the labels that each got.

#1263 BREAKING: Removing attention color from RatingStars
  src/RatingStars/README.md
  src/RatingStars/RatingStars.stories.js
  src/RatingStars/__tests__/__snapshots__/index.test.js.snap
  src/RatingStars/__tests__/index.test.js
  src/RatingStars/index.js
  src/RatingStars/index.js.flow
Labels: Review needed

#1290 UPDATE: Popover vertical position fallback calculation
  src/Popover/Popover.stories.js
  src/Popover/__tests__/__snapshots__/index.test.js.snap
  src/Popover/helpers/calculateVerticalPosition.js
  src/Popover/hooks/useDimensions.js
  src/Popover/index.js.flow
Labels: Review needed

#1280 FIX: click on customValue on Select
  src/Select/index.js
Labels: Bug, Review needed

#1270 BREAKING: Removing attention color from Text
  src/Text/README.md
  src/Text/consts.js
  src/Text/index.js
  src/Text/index.js.flow
Labels: Review needed

#1265 BREAKING: Removing attention color from Icon
  config/build.js
  src/Icon/README.md
  src/Icon/__tests__/__snapshots__/index.test.js.snap
  src/Icon/__tests__/index.test.js
  src/Icon/consts.js
  src/Icon/index.js
  src/Icon/index.js.flow
  src/Pagination/components/CompactPages.js
Labels: Review needed

#1260 BREAKING: Delete connected property in ButtonGroup
  src/ButtonGroup/ButtonGroup.stories.js
  src/ButtonGroup/README.md
  src/ButtonGroup/index.js
  src/ButtonGroup/index.js.flow
  src/Stack/Stack.stories.js
Labels: Review needed

#1206 UPDATE: Render property basis in Stack
  src/Stack/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__tests__/index.test.js
  src/Stack/helpers/getBasis.js
  src/Stack/helpers/getBasis.js.flow
  src/Stack/helpers/getViewportFlexStyles.js
  src/Stack/index.js.flow
Labels: Review needed

#1291 UPDATE: Popover adding actions prop
  src/Popover/Popover.stories.js
  src/Popover/README.MD
  src/Popover/__tests__/__snapshots__/index.test.js.snap
  src/Popover/__tests__/index.test.js
  src/Popover/components/ContentWrapper.js
  src/Popover/components/ContentWrapper.js.flow
  src/Popover/index.js
  src/Popover/index.js.flow
Labels: Review needed

#1288 NEW: Mobile and Desktop, nitromove
  src/Desktop/Desktop.stories.js
  src/Desktop/README.md
  src/Desktop/__tests__/index.test.js
  src/Desktop/index.js
  src/Desktop/index.js.flow
  src/Mobile/Mobile.stories.js
  src/Mobile/README.md
  src/Mobile/__tests__/index.test.js
  src/Mobile/index.js
  src/Mobile/index.js.flow
Labels: Review needed

#1283 UPDATE: Adding Popover align option
  src/Popover/Popover.stories.js
  src/Popover/README.MD
  src/Popover/__tests__/index.test.js
  src/Popover/components/ContentWrapper.js
  src/Popover/components/ContentWrapper.js.flow
  src/Popover/consts.js
  src/Popover/helpers/calculateHorizontalPosition.js
  src/Popover/helpers/calculateHorizontalPosition.js.flow
  src/Popover/helpers/calculatePopoverPosition.js
  src/Popover/helpers/calculatePopoverPosition.js.flow
  src/Popover/helpers/resolvePopoverHorizontal.js
  src/Popover/index.js
  src/Popover/index.js.flow
Labels: Review needed

#1292 FIX: Scrolling in long content popovers
  src/Popover/components/ContentWrapper.js
Labels: Review needed

#1267 BREAKING: Renaming min and max to minValue and maxValue on Slider
  src/Collapse/Collapse.stories.js
  src/Slider/README.md
  src/Slider/Slider.stories.js
  src/Slider/_tests_/index.test.js
  src/Slider/index.js
  src/Slider/index.js.flow
  src/hooks/useMediaQuery.js
Labels: Review needed

#1268 BREAKING: Renaming title to buttonLabel on InputFile
  src/InputFile/InputFile.stories.js
  src/InputFile/README.md
  src/InputFile/__tests__/index.test.js
  src/InputFile/index.js
  src/InputFile/index.js.flow
Labels: Review needed

#1262 BREAKING: Renaming block to fullWidth on Button
  src/Button/Button.stories.js
  src/Button/README.md
  src/Button/index.js
  src/Button/index.js.flow
  src/Modal/Modal.stories.js
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Modal/__tests__/index.test.js
  src/Popover/Popover.stories.js
  src/Popover/components/ContentWrapper.js
  src/PricingTable/PricingTable.stories.js
  src/SkipLink/SkipLink.stories.js
  src/Tooltip/components/TooltipContent.js
Labels: Review needed

#1269 BREAKING: Renaming element to renderInto on Portal
  src/Popover/index.js
  src/Portal/README.md
  src/Portal/__tests__/__snapshots__/index.test.js.snap
  src/Portal/__tests__/index.test.js
  src/Portal/index.js
  src/Portal/index.js.flow
  src/Tooltip/index.js
Labels: Review needed

#1271 BREAKING: Renaming labelElement to labelAs on ChoiceGroup
  src/ChoiceGroup/ChoiceGroup.stories.js
  src/ChoiceGroup/README.md
  src/ChoiceGroup/__tests__/index.test.js
  src/ChoiceGroup/index.js
  src/ChoiceGroup/index.js.flow
  src/Stack/Stack.stories.js
Labels: Review needed

#1294 FIX: Tooltip enabled prop behaviour
  src/Tooltip/__tests__/__snapshots__/index.test.js.snap
  src/Tooltip/index.js
Labels: Review needed

#1296 FIX: PricingTable active element border
  src/PricingTable/PricingTableItem/consts.js
  src/PricingTable/PricingTableItem/index.js
Labels: Review needed

#1301 UPDATE: Tooltip adding prop for removing underline text on children
  src/Tooltip/README.md
  src/Tooltip/Tooltip.stories.js
  src/Tooltip/index.js
  src/Tooltip/index.js.flow
Labels: Review needed

#1299 UPDATE: bigger icon for separated List
  src/List/ListItem/index.js
  src/List/ListItem/index.js.flow
  src/List/__tests__/__snapshots__/index.test.js.snap
  src/List/index.js
  src/List/index.js.flow
  src/hooks/useMediaQuery.js
Labels: Review needed

#1300 FIX: Badge overlay in PricingTable
  src/PricingTable/PricingTableItem/index.js
Labels: Review needed

#1303 FIX: Popover callback loop
  src/Popover/index.js
Labels: Review needed

#1304 UPDATE: Dynamic z-index for Popover
  src/Modal/ModalContext.js
  src/Modal/ModalContext.js.flow
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Modal/index.js
  src/Popover/__tests__/__snapshots__/index.test.js.snap
  src/Popover/components/ContentWrapper.js
Labels: Review needed

#1207 NEW: Navigation components
  src/Alert/index.js
  src/Breadcrumbs/index.js
  src/Card/index.js
  src/DestinationHeader/index.js
  src/Drawer/Drawer.stories.js
  src/Drawer/README.md
  src/Drawer/__tests__/index.test.js
  src/Drawer/components/DrawerClose.js
  src/Drawer/components/DrawerClose.js.flow
  src/Drawer/components/__tests__/DrawerClose.test.js
  src/Drawer/consts.js
  src/Drawer/helpers/__tests__/__snapshots__/getTransitionAnimation.test.js.snap
  src/Drawer/helpers/__tests__/getPosition.test.js
  src/Drawer/helpers/__tests__/getTransitionAnimation.test.js
  src/Drawer/helpers/getPosition.js
  src/Drawer/helpers/getPosition.js.flow
  src/Drawer/helpers/getTransitionAnimation.js
  src/Drawer/helpers/getTransitionAnimation.js.flow
  src/Drawer/index.js
  src/Drawer/index.js.flow
  src/Modal/index.js
  src/NavigationBar/NavigationBar.stories.js
  src/NavigationBar/README.md
  src/NavigationBar/__tests__/index.test.js
  src/NavigationBar/index.js
  src/NavigationBar/index.js.flow
  src/NavigationList/NavigationList.stories.js
  src/NavigationList/NavigationListItem/__tests__/index.test.js
  src/NavigationList/NavigationListItem/consts.js
  src/NavigationList/NavigationListItem/helpers/getCssState.js
  src/NavigationList/NavigationListItem/helpers/getCssState.js.flow
  src/NavigationList/NavigationListItem/index.js
  src/NavigationList/NavigationListItem/index.js.flow
  src/NavigationList/README.md
  src/NavigationList/__tests__/index.test.js
  src/NavigationList/components/NavigationListSeparator.js
  src/NavigationList/consts.js
  src/NavigationList/helpers/isType.js
  src/NavigationList/helpers/isType.js.flow
  src/NavigationList/index.js
  src/NavigationList/index.js.flow
  src/RatingStars/index.js
  src/data/dictionary/en-GB.json
  src/hooks/useDictionary.js
  src/hooks/useDictionary.js.flow
  src/hooks/useStateWithCallback.js
  src/hooks/useStateWithCallback.js.flow
  src/index.js
  src/index.js.flow
Labels: Review needed, Tested

#1302 UPDATE: Focus state on Buttons
  src/Alert/index.js
  src/Button/consts.js
  src/Button/helpers/getButtonBoxShadow.js
  src/Button/helpers/getFocus.js
  src/Button/helpers/getFocus.js.flow
  src/Button/helpers/getTypeToken.js
  src/Button/helpers/getTypeToken.js.flow
  src/Button/index.js
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/consts.js
  src/ButtonLink/helpers/getButtonLinkBoxShadow.js
  src/ButtonLink/helpers/getFocus.js
  src/ButtonLink/helpers/getFocus.js.flow
  src/ButtonLink/helpers/getTypeToken.js
  src/ButtonLink/helpers/getTypeToken.js.flow
  src/ButtonLink/index.js
  src/Modal/index.js
  src/Stack/__tests__/__snapshots__/index.test.js.snap
Labels: Accessibility, Review needed

#1311 NEW: FeatureIcon component
  .gitignore
  config/flowFiles.js
  src/FeatureIcon/FLOW_TEMPLATE.flow
  src/FeatureIcon/FeatureIcon.stories.js
  src/FeatureIcon/README.md
  src/FeatureIcon/__tests__/index.test.js
  src/FeatureIcon/consts.js
  src/FeatureIcon/index.js
  src/PricingTable/PricingTable.stories.js
  src/index.js
  src/index.js.flow
Labels: Review needed

#1306 NEW: useTranslate hook
  src/Alert/index.js
  src/Breadcrumbs/index.js
  src/Card/index.js
  src/DestinationHeader/index.js
  src/Drawer/components/DrawerClose.js
  src/Modal/index.js
  src/NavigationBar/index.js
  src/RatingStars/index.js
  src/Translate/index.js
  src/Translate/index.js.flow
  src/hooks/useTranslate.js
  src/hooks/useTranslate.js.flow
Labels: Review needed

#1307 FIX: Drawer header padding and DOM render
  src/Drawer/index.js
Labels: Review needed

#1308 FIX: Flow React annotation in List
  src/List/index.js.flow
Labels: Review needed

#1309 UPDATE: ListItem separated fontWeight
  src/List/ListItem/index.js
Labels: Review needed

#1315 FIX: Modal scrolling with absolutely positioned element
  src/Modal/index.js
Labels: Review needed

#1318 FIX: CountryFlag dimensions in Buttons
  src/Button/index.js
  src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
  src/ButtonLink/index.js
Labels: Review needed

#1328 FIX: Flex wrapping of Alert's content in IE
  src/Alert/index.js
Labels: Bug, IE, Review needed

#1331 FIX: Collapse onClick handler
  src/Collapse/Collapse.stories.js
  src/Collapse/index.js
Labels: Bug, Review needed

#1337 FIX: NavigationListItem flex behavior
  src/Drawer/Drawer.stories.js
  src/NavigationList/NavigationListItem/index.js
Labels: Review needed

#1336 FIX: PricingTableItem shrink
  src/PricingTable/PricingTable.stories.js
  src/PricingTable/PricingTableItem/index.js
Labels: Review needed

#1335 DOCS: Fix Coupon name in README
  src/Coupon/README.md
Labels: Review needed

#1333 DEV: Refactor Table component to React hooks
  src/Table/__tests__/__snapshots__/index.test.js.snap
  src/Table/__tests__/index.test.js
  src/Table/index.js
  src/Table/index.js.flow
Labels: Refactoring, Review needed

#1329 UPDATE: Coupon component styles
  src/Coupon/Coupon.stories.js
  src/Coupon/index.js
  src/List/ListItem/index.js
Labels: Review needed

#1334 NEW: AppQRCode illustration
  src/Illustration/README.md
  src/Illustration/consts.js
Labels: Review needed

#1338 FIX: Tooltip tabIndex render
  src/Tooltip/index.js
Labels: Review needed

#1339 NEW: useToggle hook
  src/hooks/useToggle.js
  src/hooks/useToggle.js.flow
Labels: Enhancement, Review needed

#1351 FIX: Tile's title wrapping in IE
  src/Tile/TileHeader/index.js
Labels: Bug, IE, Review needed

#1352 FIX: Collapse double handleClick firing
  src/Collapse/index.js
Labels: Bug, Review needed

#1348 DEV: Stepper to hooks
  src/Stepper/_tests_/index.test.js
  src/Stepper/index.js
  src/Stepper/index.js.flow
  src/hooks/useStateWithCallback.js
  src/hooks/useStateWithCallback.js.flow
Labels: Refactoring, Review needed

#1347 DEV: InputStepper to hooks
  src/InputStepper/index.js
  src/InputStepper/index.js.flow
  src/common/common.js.flow
Labels: Refactoring, Review needed

#1353 UPDATE: Slider onChange callbacks behaviour
  src/Slider/Slider.stories.js
  src/Slider/index.js
Labels: Review needed
