Repository kiwicom/orbit, pull requests merged in 2019-01, with the labels that each got.

#715 ADD: New icons and illustrations
  src/Button/__snapshots__/Button.stories.storyshot
  src/Icon/__snapshots__/Icon.stories.storyshot
  src/Illustration/README.md
  src/Illustration/consts.js
  src/Illustration/index.js.flow
  src/icons/svg/baggage-cabin-none.svg
  src/icons/svg/baggage-cabin.svg
  src/icons/svg/baggage-personal-item-none.svg
  src/icons/svg/chart.svg
  src/icons/svg/remove.svg
  src/icons/svg/timer.svg
Labels: Icons, Illustrations, Review needed

#706 FIX: InputStepper null minValue or maxValue
  src/InputStepper/index.js
Labels: Bug

#716 FIX: Flow: Unnecessary Button SyntheticKeyboardEvent
  src/ButtonLink/index.js.flow
Labels: Review needed

#720 FIX: Badge
  src/Badge/__snapshots__/Badge.stories.storyshot
  src/Badge/index.js
  src/Card/__snapshots__/Card.stories.storyshot
Labels: Review needed

#691 FIX: Text wrong weight value
  src/Text/README.md
  src/Text/index.js
  src/Text/index.js.flow
Labels: Bug, Review needed

#725 DOCS: Add styled-components to installation guide
  readme.md
Labels: Documentation

#709 UPDATE: Add size to TextLink
  src/Checkbox/__snapshots__/Checkbox.stories.storyshot
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/Radio/__snapshots__/Radio.stories.storyshot
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/TextLink/README.md
  src/TextLink/TextLink.stories.js
  src/TextLink/__snapshots__/TextLink.stories.storyshot
  src/TextLink/consts.js
  src/TextLink/index.js
  src/TextLink/index.js.flow
  src/TripSector/__snapshots__/TripSector.stories.storyshot
Labels: Enhancement, Review needed

#710 FIX: Remove webkit spin from InputField
  src/InputField/README.md
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputField/index.js
  src/InputGroup/__snapshots__/InputGroup.stories.storyshot
  src/InputStepper/__snapshots__/InputStepper.stories.storyshot
  src/InputStepper/__tests__/__snapshots__/index.test.js.snap
  src/InputStepper/index.js
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/Stack/__tests__/__snapshots__/index.test.js.snap
Labels: Bug, Documentation, Review needed

#704 UPDATE: Modal usage without ModalSection
  src/Modal/Modal.stories.js
  src/Modal/ModalContext.js
  src/Modal/ModalContext.js.flow
  src/Modal/ModalHeader/index.js
  src/Modal/ModalHeader/index.js.flow
  src/Modal/ModalSection/index.js
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Modal/__tests__/__snapshots__/index.test.js.snap
  src/Modal/index.js
  src/Modal/index.js.flow
Labels: Enhancement, Review needed

#735 FIX: TripSector docs imports
  src/TripSector/README.md
Labels: Documentation

#732 ADD: passportid type to InputField
  src/InputField/InputField.stories.js
  src/InputField/README.md
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputField/consts.js
  src/InputField/index.js
  src/InputField/index.js.flow
  src/InputGroup/__snapshots__/InputGroup.stories.storyshot
  src/InputStepper/__snapshots__/InputStepper.stories.storyshot
  src/InputStepper/__tests__/__snapshots__/index.test.js.snap
  src/Modal/__snapshots__/Modal.stories.storyshot
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/Stack/__tests__/__snapshots__/index.test.js.snap
Labels: Review needed

#731 ADD: inlineLoader type to Loading
  src/Loading/Loading.stories.js
  src/Loading/README.md
  src/Loading/__snapshots__/Loading.stories.storyshot
  src/Loading/consts.js
  src/Loading/index.js
  src/Loading/index.js.flow
Labels: Review needed

#730 FIX: Odd TableRow background color
  src/Stack/__snapshots__/Stack.stories.storyshot
  src/Table/__snapshots__/Table.stories.storyshot
  src/Table/index.js
Labels: Review needed

#737 FIX: Modal docs default size
  src/Modal/README.md
Labels: Documentation

#741 FIX: InputField missing ref
  src/InputField/__tests__/index.test.js
  src/InputField/index.js
  src/InputStepper/__tests__/__snapshots__/index.test.js.snap
  src/Stack/__tests__/__snapshots__/index.test.js.snap
Labels: Review needed

#444 UPDATE: FLOW: Restricted Translation in some components
  src/Alert/index.js.flow
  src/Badge/index.js.flow
  src/ChoiceGroup/index.js.flow
  src/InputField/index.js
  src/InputField/index.js.flow
  src/InputFile/index.js.flow
  src/InputGroup/index.js.flow
  src/InputStepper/index.js.flow
  src/ListChoice/index.js.flow
  src/Loading/index.js.flow
  src/Select/index.js.flow
  src/Textarea/index.js.flow
  src/Tile/TileHeader/index.js.flow
  src/Tile/index.js.flow
  src/common/common.js.flow
Labels: Review needed

#591 NEW: Stepper component
  src/Stepper/README.md
  src/Stepper/Stepper.stories.js
  src/Stepper/__snapshots__/Stepper.stories.storyshot
  src/Stepper/_tests_/__snapshots__/index.test.js.snap
  src/Stepper/_tests_/index.test.js
  src/Stepper/index.js
  src/Stepper/index.js.flow
  src/index.js
  src/index.js.flow
Labels: Review needed

#744 FIX: Translation docs
  src/Alert/README.md
  src/ChoiceGroup/README.md
  src/InputField/README.md
  src/InputFile/README.md
  src/InputGroup/README.md
  src/InputStepper/README.md
  src/ListChoice/README.md
  src/Loading/README.md
  src/Select/README.md
  src/Textarea/README.md
  src/Tile/README.md
Labels: Documentation

#650 UPDATE: Add Inputfield readOnly prop
  src/InputField/InputField.stories.js
  src/InputField/README.md
  src/InputField/__snapshots__/InputField.stories.storyshot
  src/InputField/__tests__/__snapshots__/index.test.js.snap
  src/InputField/__tests__/index.test.js
  src/InputField/index.js
  src/InputField/index.js.flow
Labels: Review needed

#785 FIX: ModalFooter string as children
  src/Modal/ModalFooter/index.js
  src/Modal/__tests__/index.test.js
Labels: Review needed

#778 UPDATE: ChoiceGroup replace hasError for error
  src/ChoiceGroup/ChoiceGroup.stories.js
  src/ChoiceGroup/README.md
  src/ChoiceGroup/__snapshots__/ChoiceGroup.stories.storyshot
  src/ChoiceGroup/__tests__/__snapshots__/index.test.js.snap
  src/ChoiceGroup/index.js
  src/ChoiceGroup/index.js.flow
  src/FormFeedback/index.js
  src/FormFeedback/index.js.flow
  src/Stack/__snapshots__/Stack.stories.storyshot
Labels: Review needed
