Repository kiwicom/orbit, pull requests merged in 2020-11, with the labels that each got.

#2391 feat(AlertButton): set small as default size for alert button
  packages/orbit-components/src/Alert/Alert.stories.js
  packages/orbit-components/src/Alert/AlertButton/index.d.ts
  packages/orbit-components/src/Alert/AlertButton/index.js
  packages/orbit-components/src/Alert/AlertButton/index.js.flow
  packages/orbit-components/src/Alert/README.md
  packages/orbit-components/src/Alert/__examples__/CRITICAL_TYPE.js
  packages/orbit-components/src/Alert/__examples__/INFO_TYPE.js
  packages/orbit-components/src/Alert/__examples__/INLINE_ACTIONS.js
  packages/orbit-components/src/Alert/__examples__/WARNING_TYPE.js
Labels: hacktoberfest-accepted

#2451 improve: add codemod for spacing of Stack
  packages/orbit-components/transforms/Stack-spacing.js
  packages/orbit-components/transforms/__testfixtures__/Stack-spacing.input.js
  packages/orbit-components/transforms/__testfixtures__/Stack-spacing.output.js
  packages/orbit-components/transforms/__tests__/Stack-spacing.test.js
Labels: Review needed

#2465 ci: force cli colors on GitHub Workflows
  .github/workflows/deploy_master.yml
  .github/workflows/main.yml
  .github/workflows/test.yml
Labels: Review needed

#2468 fix(Stack): change spacing value TS types
  packages/orbit-components/src/Stack/index.d.ts
Labels: Review needed

#2411 refactor(Modal): use hooks
  packages/orbit-components/src/Modal/ModalCloseButton/index.d.ts
  packages/orbit-components/src/Modal/ModalCloseButton/index.js
  packages/orbit-components/src/Modal/ModalCloseButton/index.js.flow
  packages/orbit-components/src/Modal/__tests__/__snapshots__/index.test.js.snap
  packages/orbit-components/src/Modal/__tests__/index.test.js
  packages/orbit-components/src/Modal/index.d.ts
  packages/orbit-components/src/Modal/index.js
  packages/orbit-components/src/hooks/usePrevious/index.js
Labels: Review needed

#2426 feat(Button): div behave like button, a11y
  packages/orbit-components/src/primitives/ButtonPrimitive/__tests__/index.test.js
  packages/orbit-components/src/primitives/ButtonPrimitive/index.js
Labels: Accessibility, Review needed

#2504 feat: SmartPassIllustration component
  packages/orbit-components/.gitignore
  packages/orbit-components/src/SmartPassIllustration/README.md
  packages/orbit-components/src/SmartPassIllustration/SmartPassIllustration.stories.js
  packages/orbit-components/src/SmartPassIllustration/__tests__/index.test.js
  packages/orbit-components/src/SmartPassIllustration/components/SmartPassV1.js
  packages/orbit-components/src/SmartPassIllustration/components/SmartPassV2.js
  packages/orbit-components/src/SmartPassIllustration/components/SmartPassV3.js
  packages/orbit-components/src/SmartPassIllustration/components/SmartPassV4.js
  packages/orbit-components/src/SmartPassIllustration/components/index.js
  packages/orbit-components/src/SmartPassIllustration/index.d.ts
  packages/orbit-components/src/SmartPassIllustration/index.js
  packages/orbit-components/src/SmartPassIllustration/index.js.flow
  packages/orbit-components/src/index.d.ts
  packages/orbit-components/src/index.js
  packages/orbit-components/src/index.js.flow
Labels: Review needed

#2541 docs: create basic setup for new docs
  .eslintignore
  .eslintrc.js
  config/eslintJS.js
  docs/.eslintrc.js
  docs/.gitignore
  docs/babel.config.js
  docs/css-prop.d.ts
  docs/gatsby-browser.js
  docs/gatsby-config.js
  docs/gatsby-node.js
  docs/package.json
  docs/src/components/Code.tsx
  docs/src/components/Layout.tsx
  docs/src/components/Prose.tsx
  docs/src/components/RocketImage.tsx
  docs/src/guides/developers/using-component-types.mdx
  docs/src/images/rocket.jpg
  docs/src/mdx-components.tsx
  docs/src/pages/index.tsx
  docs/src/templates/Guide.tsx
  docs/src/theme.tsx
  docs/styled.d.ts
  gulpfile.js
  lerna.json
  package.json
  tsconfig.json
  yarn.lock
Labels: Documentation, Review needed
