Repository kiwicom/orbit, pull requests merged in 2020-03, with the labels that each got.

#1570 FIX: Card text wrapping IE issue
  src/Card/components/Header/index.js
Labels: Review needed

#1580 DEV: Add Stack helper tests
  src/Stack/helpers/__tests__/getAlign.test.js
  src/Stack/helpers/__tests__/getBasis.test.js
  src/Stack/helpers/__tests__/getDesktopSpacing.test.js
  src/Stack/helpers/__tests__/getDirection.test.js
  src/Stack/helpers/__tests__/getDisplay.test.js
  src/Stack/helpers/__tests__/getGrow.test.js
  src/Stack/helpers/__tests__/getJustify.test.js
  src/Stack/helpers/__tests__/getMobileSpacing.test.js
  src/Stack/helpers/__tests__/getProperty.test.js
  src/Stack/helpers/__tests__/getShrink.test.js
  src/Stack/helpers/__tests__/getWidth.test.js
  src/Stack/helpers/__tests__/getWrap.test.js
  src/Stack/helpers/__tests__/shouldUseFlex.test.js
Labels: Review needed

#1601 DOCS: Add documentation to useMediaQuery hook
  src/hooks/useMediaQuery/README.md
Labels: Documentation, Review needed

#1579 DEV: Utilize handleKeyDown function
  src/Alert/index.js
  src/ListChoice/index.js
  src/PictureCard/index.js
  src/Tile/components/TileExpandable/index.js
  src/Tile/index.js
  src/deprecated/DestinationCard/index.js
  src/utils/handleKeyDown/index.js
  src/utils/handleKeyDown/index.js.flow
Labels: Review needed

#1616 FIX: Modal close on mobile devices
  src/Modal/index.js
Labels: Review needed

#1600 UPDATE: Add type definitions to QUERIES and DEVICES in mediaQuery
  src/Hide/helpers/getViewportHideStyles.js.flow
  src/Hide/index.js.flow
  src/Layout/LayoutColumn/index.js.flow
  src/Stack/helpers/getChildrenMargin.js.flow
  src/Stack/helpers/getProperty.js.flow
  src/Stack/helpers/getViewportFlexStyles.js.flow
  src/Stack/helpers/isMobileViewport.js.flow
  src/utils/Grid/helpers/getProperty.js.flow
  src/utils/Grid/helpers/getViewportGridStyles.js.flow
  src/utils/Grid/helpers/getViewportIEGridStyles.js.flow
  src/utils/mediaQuery/consts.js.flow
  src/utils/mediaQuery/index.js.flow
Labels: Review needed

#1633 DEV: Update storybook plugins
  package.json
  yarn.lock
Labels: Review needed

#1585 FIX: Mobile Card edge to edge breakpoint
  src/Card/CardSection/components/SectionContent.js
  src/Card/CardSection/components/SectionHeader.js
  src/Card/components/CardWrapper/index.js
  src/Card/helpers/mixins.js
Labels: Review needed

#1632 DEV: Update babel dependencies
  package.json
  yarn.lock
Labels: Review needed

#1617 DEV: Fix ChoiceGroup a11y in tests
  src/ChoiceGroup/__tests__/index.test.js
Labels: Review needed

#1590 UPDATE: Tooltip sync with native design
  src/Tooltip/components/TooltipContent.js
  src/Tooltip/helpers/__tests__/tooltipArrowStyle.test.js
  src/Tooltip/helpers/tooltipArrowStyle.js
Labels: Review needed

#1634 UPDATE: Add dataAttrs property to InputField and Select
  src/InputField/InputField.stories.js
  src/InputField/README.md
  src/InputField/__tests__/index.test.js
  src/InputField/index.js
  src/InputField/index.js.flow
  src/Select/README.md
  src/Select/Select.stories.js
  src/Select/__tests__/Select.test.js
  src/Select/index.js
  src/Select/index.js.flow
  src/common/common.js.flow
Labels: Review needed

#1577 UPDATE: Radio sync with native desing
  src/Radio/index.js
Labels: Review needed

#1576 UPDATE: Checkbox sync with native desing
  src/Checkbox/Checkbox.stories.js
  src/Checkbox/index.js
Labels: Review needed

#1575 UPDATE: Alert sync with native design
  src/Alert/Alert.stories.js
  src/Alert/index.js
Labels: Review needed

#1571 DEV: Add Github action for compressed bundle size
  .github/workflows/main.yml
Labels: Changes requested

#1641 FIX: Persistent tooltipId on SSR
  src/Tooltip/__tests__/__snapshots__/index.test.js.snap
  src/Tooltip/components/TooltipContent.js.flow
  src/Tooltip/index.js
Labels: Review needed

#1589 UPDATE: Popover sync with native design
  src/Popover/components/ContentWrapper.js
Labels: Review needed

#1588 UPDATE: Modal sync with native design
  src/Modal/Modal.stories.js
  src/Modal/ModalFooter/index.js
  src/Modal/ModalHeader/index.js
  src/Modal/ModalSection/index.js
  src/Modal/index.js
Labels: Review needed

#1587 UPDATE: Sync Dialog with native design
  src/Dialog/Dialog.stories.js
  src/Dialog/README.md
  src/Dialog/index.js
  src/Dialog/index.js.flow
Labels: Review needed

#1582 UPDATE: Add ferry and private_transfer types to CarrierLogo
  src/CarrierLogo/README.md
  src/CarrierLogo/consts.js
  src/CarrierLogo/index.js.flow
Labels: Review needed

#1574 UPDATE: Sync visual style of Badge with native designs
  src/Badge/_tests_/index.test.js
  src/Badge/consts.js
  src/Badge/index.js
  src/primitives/BadgePrimitive/README.md
  src/primitives/BadgePrimitive/index.js
  src/primitives/BadgePrimitive/index.js.flow
  src/primitives/Primitives.stories.js
Labels: Review needed

#1586 UPDATE: FormElements native sync
  src/InputField/InputField.stories.js
  src/InputField/index.js
  src/InputFile/index.js
  src/InputGroup/index.js
  src/Radio/Radio.stories.js
  src/Select/index.js
  src/Textarea/Textarea.stories.js
  src/Textarea/index.js
Labels: Review needed

#1581 UPDATE: Change Modal title size to title2
  src/Modal/ModalHeader/index.js
  src/Modal/ModalHeader/index.js.flow
  src/Modal/index.js
Labels: Changes requested

#1666 fix(Breadcrumbs): add correct html5 structured microdata for breadcrumbs
  src/Breadcrumbs/Breadcrumbs.stories.js
  src/Breadcrumbs/BreadcrumbsItem/index.js
  src/Breadcrumbs/_tests_/index.test.js
  src/Breadcrumbs/index.js
Labels: Enhancement, Review needed

#1680 fix(tooltip): usage of TextLink in content
  src/Tooltip/Tooltip.stories.js
  src/Tooltip/components/TooltipContent.js
Labels: Review needed

#1668 feat(theme): Added transitions property
  .github/theming.md
  src/Card/CardSection/components/SectionContent.js
  src/Card/CardSection/components/SectionHeader.js
  src/Card/components/CardWrapper/index.js
  src/Card/components/Header/index.js
  src/Drawer/index.js
  src/Modal/ModalFooter/index.js
  src/Modal/ModalHeader/index.js
  src/Modal/index.js
  src/NavigationBar/index.js
  src/Popover/components/ContentWrapper.js
  src/Separator/__tests__/__snapshots__/index.test.js.snap
  src/Slider/components/Handle/index.js
  src/Slider/index.js
  src/ThemeProvider/README.md
  src/ThemeProvider/ThemeProvider.stories.js
  src/ThemeProvider/index.js
  src/ThemeProvider/index.js.flow
  src/Tile/components/TileHeader/index.js
  src/Tile/components/TileWrapper/index.js
  src/Tooltip/components/TooltipContent.js
  src/defaultTheme.js
  src/defaultTheme.js.flow
  src/utils/Slide/index.js
  src/utils/transition/__tests__/index.test.js
  src/utils/transition/index.js
  src/utils/transition/index.js.flow
Labels: Review needed

#1345 DEV: Refactor Modal subcomponents to React hooks
  src/Modal/Modal.stories.js
  src/Modal/ModalContext.js
  src/Modal/ModalContext.js.flow
  src/Modal/ModalFooter/index.js
  src/Modal/ModalFooter/index.js.flow
  src/Modal/ModalHeader/index.js
  src/Modal/ModalHeader/index.js.flow
  src/Modal/ModalSection/index.js
  src/Modal/ModalSection/index.js.flow
  src/Modal/helpers/useModalContextFunctions.js
  src/Modal/helpers/useModalContextFunctions.js.flow
  src/Modal/index.js
Labels: Review needed, Tested

#1687 refactor: Remove unnecessary pixels in CSS declarations
  src/Card/components/Header/index.js
  src/Checkbox/index.js
  src/Radio/index.js
  src/SkipLink/index.js
  src/Tag/index.js
  src/TextLink/index.js
Labels: Review needed

#1728 fix(radar): SVG definition
  src/icons/svg/radar.svg
Labels: Review needed

#1726 fix(modal): border radius of close container on desktop
  src/Modal/index.js
Labels: Review needed

#1732 feat(Tile): make tile padding large on desktop viewport
  src/Tile/components/TileContent/index.js
  src/Tile/components/TileHeader/index.js
Labels: Enhancement

#1741 style(slider): updating color
  src/Slider/components/Bar/index.js
  src/Slider/components/Handle/index.js
  src/Slider/components/Histogram/index.js
Labels: Review needed

#1742 fix(Tooltip): should close when clicked on clickable element
  src/Tooltip/Tooltip.stories.js
  src/Tooltip/components/TooltipContent.js
Labels: Review needed

#1740 fix(Hide): omit rendering of on property
  src/Hide/index.js
Labels: Review needed

#1739 fix(Modal): click ability under CloseContainer
  src/Modal/index.js
Labels: Review needed
