Repository kiwicom/orbit, pull requests merged in 2020-01, with the labels that each got.

#1420 FIX: Card header prop, padding in CardSection
  src/Card/CardSection/components/SectionHeader.js
  src/Card/CardSection/index.js
  src/Card/index.js
Labels: Bug, Review needed

#1417 FIX: ChoiceGroup only selection with disabled
  src/ChoiceGroup/ChoiceGroup.stories.js
  src/ChoiceGroup/components/FilterWrapper.js
Labels: Bug, Review needed

#1418 FIX: PricingTable dataTest render
  src/PricingTable/PricingTableItem/index.js
  src/PricingTable/__tests__/index.test.js
  src/PricingTable/index.js
Labels: Review needed

#1416 FIX: Missing shrink on Stack in Card
  src/Card/components/Header.js
  src/Card/index.js
Labels: Bug, Review needed

#1422 FIX: Badge overflow in Pricing table
  src/PricingTable/PricingTable.stories.js
  src/PricingTable/PricingTableItem/index.js
Labels: Review needed

#1430 FIX: useMediaQuery incorrect cleanup reference
  src/hooks/useMediaQuery/index.js
Labels: Review needed

#1429 BREAKING: Rename block to fullWidth on ButtonLink
  src/ButtonLink/ButtonLink.stories.js
  src/ButtonLink/README.md
  src/ButtonLink/index.js
  src/ButtonLink/index.js.flow
Labels: Breaking

#1406 DEV: Refactor LazyImage component
  src/DestinationCard/index.js.flow
  src/DestinationHeader/index.js.flow
  src/LazyImage/index.js
  src/LazyImage/index.js.flow
Labels: Review needed

#1431 NEW: Dialog component
  src/Dialog/Dialog.stories.js
  src/Dialog/README.md
  src/Dialog/__tests__/index.test.js
  src/Dialog/index.js
  src/Dialog/index.js.flow
  src/common/keyMaps.js
  src/index.js
  src/index.js.flow
Labels: Review needed

#1407 NEW: PictureCard component
  src/PictureCard/PictureCard.stories.js
  src/PictureCard/README.md
  src/PictureCard/__tests__/index.test.js
  src/PictureCard/consts.js
  src/PictureCard/index.js
  src/PictureCard/index.js.flow
  src/deprecated/DestinationCard/DestinationCard.stories.js
  src/deprecated/DestinationCard/README.md
  src/deprecated/DestinationCard/_tests_/index.test.js
  src/deprecated/DestinationCard/consts.js
  src/deprecated/DestinationCard/index.js
  src/deprecated/DestinationCard/index.js.flow
  src/deprecated/README.md
  src/index.js
  src/index.js.flow
Labels: Review needed

#1376 UPDATE: Making focus states consistent
  src/Alert/consts.js
  src/Alert/index.js
  src/Button/helpers/getTypeToken.js
  src/Checkbox/index.js
  src/InputField/helpers/formElementFocus.js
  src/InputField/index.js
  src/InputFile/index.js
  src/InputGroup/index.js
  src/InputStepper/InputStepperStateless/index.js
  src/Radio/index.js
  src/Select/index.js
  src/Tag/index.js
  src/TextLink/index.js
  src/Textarea/index.js
Labels: Review needed

#1477 FIX: Modal scrolling with absolute element and fixedFooter
  src/Modal/index.js
Labels: Review needed

#1484 NEW: TileGroup component
  src/Tile/components/TileWrapper/index.js
  src/Tile/components/TileWrapper/index.js.flow
  src/TileGroup/README.md
  src/TileGroup/TileGroup.stories.js
  src/TileGroup/__tests__/index.test.js
  src/TileGroup/index.js
  src/TileGroup/index.js.flow
  src/index.js
  src/index.js.flow
Labels: Review needed

#1485 FIX: Modal without onClose rendering CloseContainer
  src/Modal/ModalContext.js
  src/Modal/ModalContext.js.flow
  src/Modal/ModalSection/index.js
  src/Modal/index.js
Labels: Review needed

#1424 BREAKING: Delete NavigationList, introduce LinkList component
  src/Collapse/index.js
  src/Collapse/index.js.flow
  src/Drawer/Drawer.stories.js
  src/Drawer/__tests__/index.test.js
  src/Drawer/index.js
  src/LinkList/README.md
  src/LinkList/__tests___/index.test.js
  src/LinkList/index.js
  src/LinkList/index.js.flow
  src/NavigationBar/NavigationBar.stories.js
  src/NavigationBar/index.js
  src/NavigationList/NavigationList.stories.js
  src/NavigationList/NavigationListItem/__tests__/index.test.js
  src/NavigationList/NavigationListItem/consts.js
  src/NavigationList/NavigationListItem/helpers/getCssState.js
  src/NavigationList/NavigationListItem/helpers/getCssState.js.flow
  src/NavigationList/NavigationListItem/index.js
  src/NavigationList/NavigationListItem/index.js.flow
  src/NavigationList/README.md
  src/NavigationList/__tests__/index.test.js
  src/NavigationList/components/NavigationListSeparator.js
  src/NavigationList/consts.js
  src/NavigationList/helpers/isType.js
  src/NavigationList/helpers/isType.js.flow
  src/NavigationList/index.js
  src/NavigationList/index.js.flow
  src/index.js
  src/index.js.flow
Labels: Breaking, Review needed

#1496 NEW: useFocusTrap hook
  src/Dialog/index.js
  src/Modal/consts.js
  src/Modal/index.js
  src/hooks/useFocusTrap/README.md
  src/hooks/useFocusTrap/consts.js
  src/hooks/useFocusTrap/index.js
  src/hooks/useFocusTrap/index.js.flow
Labels: Review needed

#1500 FIX: LayoutColumn passing props
  src/Layout/Layout.stories.js
  src/Layout/LayoutColumn/index.js
  src/Layout/README.md
  src/Layout/__tests__/index.test.js
  src/Layout/index.js
Labels: Review needed
