Repository kiwicom/orbit, pull requests merged in 2020-10, with the labels that each got.

#2277 fix(Hide): span to div
  packages/orbit-components/src/Hide/index.js
Labels: Review needed

#2312 feat(Illustration): added image to images.kiwi
  packages/orbit-components/src/Illustration/README.md
  packages/orbit-components/src/Illustration/consts.js
Labels: Review needed

#2330 improve(Commitlint): add the improve type to commitlint
  commitlint.config.js
Labels: hacktoberfest-accepted

#2340 fix(ModalSection): margin-top
  packages/orbit-components/src/Modal/ModalSection/index.js
Labels: Review needed

#2287 feat(Timeline): init component
  packages/babel-plugin-orbit-components/index.js
  packages/orbit-components/src/Modal/ModalContext.js
  packages/orbit-components/src/Modal/ModalContext.js.flow
  packages/orbit-components/src/Timeline/README.md
  packages/orbit-components/src/Timeline/Timeline.stories.js
  packages/orbit-components/src/Timeline/TimelineContext.js
  packages/orbit-components/src/Timeline/TimelineContext.js.flow
  packages/orbit-components/src/Timeline/TimelineStep/__tests__/index.test.js
  packages/orbit-components/src/Timeline/TimelineStep/components/CustomBadge.js
  packages/orbit-components/src/Timeline/TimelineStep/components/TimelineStepDesktop.js
  packages/orbit-components/src/Timeline/TimelineStep/components/TimelineStepMobile.js
  packages/orbit-components/src/Timeline/TimelineStep/index.d.ts
  packages/orbit-components/src/Timeline/TimelineStep/index.js
  packages/orbit-components/src/Timeline/TimelineStep/index.js.flow
  packages/orbit-components/src/Timeline/TimelineStep/primitives/StyledIconWrapper.js
  packages/orbit-components/src/Timeline/TimelineStep/primitives/StyledProgressLine.js
  packages/orbit-components/src/Timeline/TimelineStep/primitives/StyledRelative.js
  packages/orbit-components/src/Timeline/TimelineStep/primitives/StyledText.js
  packages/orbit-components/src/Timeline/__tests__/index.test.js
  packages/orbit-components/src/Timeline/index.d.ts
  packages/orbit-components/src/Timeline/index.js
  packages/orbit-components/src/Timeline/index.js.flow
  packages/orbit-components/src/index.d.ts
  packages/orbit-components/src/index.js
  packages/orbit-components/src/index.js.flow
Labels: Review needed

#2338 fix: add padding to InputField text suffix
  packages/orbit-components/examples/InputField/SUFFIX.json
  packages/orbit-components/src/InputField/__examples__/SUFFIX.js
Labels: hacktoberfest-accepted

#2356 feat(Grid): add width property
  packages/orbit-components/src/utils/Grid/Grid.stories.js
  packages/orbit-components/src/utils/Grid/README.md
  packages/orbit-components/src/utils/Grid/__tests__/index.test.js
  packages/orbit-components/src/utils/Grid/helpers/getViewportGridStyles.js
  packages/orbit-components/src/utils/Grid/index.d.ts
  packages/orbit-components/src/utils/Grid/index.js
  packages/orbit-components/src/utils/Grid/index.js.flow
Labels: Review needed

#2365 fix(TextLink): ariaCurrent should in optional in TS definition
  packages/orbit-components/src/TextLink/index.d.ts
Labels: Review needed

#2383 chore(BabelPlugin): move devDependency to peer
  packages/babel-plugin-orbit-components/package.json
Labels: Review needed, hacktoberfest, hacktoberfest-accepted

#2385 chore: move devDependencies to root
  config/eslintJS.js
  package.json
  packages/babel-plugin-orbit-components/package.json
  packages/orbit-components/package.json
Labels: Review needed, dependency, hacktoberfest, hacktoberfest-accepted

#2389 feat(Loki): skip code blocks
  packages/orbit-components/.storybook/orbitDecorator.js
  packages/orbit-components/package.json
Labels: Review needed, hacktoberfest, hacktoberfest-accepted

#2394 refactor(Storybook): hide Code in TEST env
  package.json
  packages/orbit-components/.storybook/orbitDecorator.js
  packages/orbit-components/package.json
Labels: Review needed, hacktoberfest, hacktoberfest-accepted

#2377 feat(ButtonLink)!: remove background for compact, delete inline type
  packages/orbit-components/examples/CallOutBanner/DEFAULT.json
  packages/orbit-components/examples/CallOutBanner/STRUCTURED_CONTENT.json
  packages/orbit-components/examples/Collapse/ACTIONS.json
  packages/orbit-components/examples/TextLink/ACCESSIBILITY.json
  packages/orbit-components/examples/TextLink/AS.json
  packages/orbit-components/examples/TextLink/EXTERNAL_REL.json
  packages/orbit-components/examples/TextLink/ICONS.json
  packages/orbit-components/src/Breadcrumbs/index.d.ts
  packages/orbit-components/src/Breadcrumbs/index.js
  packages/orbit-components/src/Breadcrumbs/index.js.flow
  packages/orbit-components/src/ButtonLink/ButtonLink.stories.js
  packages/orbit-components/src/ButtonLink/README.md
  packages/orbit-components/src/ButtonLink/__examples__/INLINE.js
  packages/orbit-components/src/ButtonLink/consts.js
  packages/orbit-components/src/ButtonLink/helpers/getButtonLinkIconForeground.js
  packages/orbit-components/src/ButtonLink/helpers/getButtonLinkIconForeground.js.flow
  packages/orbit-components/src/ButtonLink/helpers/getButtonLinkStyles.js
  packages/orbit-components/src/ButtonLink/helpers/getButtonLinkStyles.js.flow
  packages/orbit-components/src/ButtonLink/helpers/getButtonLinkTypeToken.js
  packages/orbit-components/src/ButtonLink/index.d.ts
  packages/orbit-components/src/ButtonLink/index.js
  packages/orbit-components/src/ButtonLink/index.js.flow
  packages/orbit-components/src/CallOutBanner/__examples__/DEFAULT.js
  packages/orbit-components/src/CallOutBanner/__examples__/STRUCTURED_CONTENT.js
  packages/orbit-components/src/Collapse/__examples__/ACTIONS.js
  packages/orbit-components/src/InputField/InputField.stories.js
  packages/orbit-components/src/InputField/__examples__/SUFFIX.js
  packages/orbit-components/src/InputField/__tests__/index.test.js
  packages/orbit-components/src/InputFile/index.js
  packages/orbit-components/src/InputStepper/InputStepperStateless/index.js
  packages/orbit-components/src/examples.js
Labels: Design review needed, Review needed

#2386 docs: Create guide on how to use component types
  docs/guides/how-to-use-component-types.md
Labels: Review needed, hacktoberfest-accepted
