Repository kiwicom/orbit, pull requests merged in 2022-10, with the labels that each got.

#3605 docs: documentation updates
  docs/src/data/component-status.yaml
Labels: Icons, Documentation

#3609 docs: fix typos and wrong links
  docs/src/documentation/03-components/12-layout/box/01-guidelines.mdx
  docs/src/documentation/03-components/12-layout/grid/01-guidelines.mdx
  docs/src/documentation/03-components/12-layout/inline/01-guidelines.mdx
  docs/src/documentation/03-components/12-layout/layout/01-guidelines.mdx
  docs/src/documentation/03-components/12-layout/stack/01-guidelines.mdx
Labels: Hacktoberfest

#3606 fix(Accordion): not expanding
  packages/orbit-components/src/Accordion/Accordion.stories.jsx
  packages/orbit-components/src/Accordion/index.jsx
Labels: Hacktoberfest

#3623 fix(Grid): fix TypeScript type for spaceAfter in Grid
  packages/orbit-components/src/utils/Grid/index.d.ts
Labels: Hacktoberfest, hacktoberfest-accepted

#3630 feat(icons): update icons from Figma
  packages/orbit-components/src/icons/svg/copy.svg
Labels: Icons
